//go:build !js || !wasm

// Code generated by gux; DO NOT EDIT.
// Server-side implementation - queries database directly.
package api

import (
	"gorm.io/gorm"

	"github.com/dougbarrett/gux/examples/admin/models"

	"github.com/dougbarrett/gux/examples/admin/dto"
)

var db *gorm.DB

// Init initializes the API with a database connection.
// Called automatically by the gux framework.
func Init(database *gorm.DB) {
	db = database
}

// UsersAPI provides CRUD operations for User.
type UsersAPI struct{}

// Users is the API client for User operations.
var Users = &UsersAPI{}

// List returns all User records.
func (a *UsersAPI) List(callback func([]dto.UserList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var items []models.User
	if err := db.Find(&items).Error; err != nil {
		callback(nil, err)
		return
	}
	// Convert to DTOs using field mappings from gux tags
	result := make([]dto.UserList, len(items))
	for i, item := range items {
		result[i] = dto.UserList{
			ID: item.ID,
			Email: item.Email,
			Name: item.Name,
			Role: item.Role,
			Status: item.Status,
			CreatedAt: item.CreatedAt,
		}
	}
	callback(result, nil)
}

// Get returns a single User by ID.
func (a *UsersAPI) Get(id uint, callback func(*dto.UserDetail, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var item models.User
	if err := db.First(&item, id).Error; err != nil {
		callback(nil, err)
		return
	}
	result := &dto.UserDetail{
			ID: item.ID,
			Email: item.Email,
			Name: item.Name,
			Role: item.Role,
			Status: item.Status,
			CreatedAt: item.CreatedAt,
			UpdatedAt: item.UpdatedAt,
	}
	callback(result, nil)
}

// Create creates a new User (server-side stub - actual creation handled by CRUD endpoint).
func (a *UsersAPI) Create(data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	// Server-side: this is typically not called directly
	// The CRUD endpoint handles creation with hooks
	callback(nil, nil)
}

// Update updates an existing User (server-side stub).
func (a *UsersAPI) Update(id uint, data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	// Server-side: this is typically not called directly
	callback(nil, nil)
}

// Delete deletes a User by ID (server-side stub).
func (a *UsersAPI) Delete(id uint, callback func(error)) {
	// Server-side: this is typically not called directly
	callback(nil)
}

// ActivityLogsAPI provides CRUD operations for ActivityLog.
type ActivityLogsAPI struct{}

// ActivityLogs is the API client for ActivityLog operations.
var ActivityLogs = &ActivityLogsAPI{}

// List returns all ActivityLog records.
func (a *ActivityLogsAPI) List(callback func([]dto.ActivityLogList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var items []models.ActivityLog
	if err := db.Find(&items).Error; err != nil {
		callback(nil, err)
		return
	}
	// Convert to DTOs using field mappings from gux tags
	result := make([]dto.ActivityLogList, len(items))
	for i, item := range items {
		result[i] = dto.ActivityLogList{
			ID: item.ID,
			Action: item.Action,
			Entity: item.Entity,
			Description: item.Description,
			CreatedAt: item.CreatedAt,
		}
	}
	callback(result, nil)
}

// Get returns a single ActivityLog by ID.
func (a *ActivityLogsAPI) Get(id uint, callback func(*dto.ActivityLogList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var item models.ActivityLog
	if err := db.First(&item, id).Error; err != nil {
		callback(nil, err)
		return
	}
	result := &dto.ActivityLogList{
			ID: item.ID,
			Action: item.Action,
			Entity: item.Entity,
			Description: item.Description,
			CreatedAt: item.CreatedAt,
	}
	callback(result, nil)
}

// Create creates a new ActivityLog (server-side stub - actual creation handled by CRUD endpoint).
func (a *ActivityLogsAPI) Create(data map[string]interface{}, callback func(*dto.ActivityLogList, error)) {
	// Server-side: this is typically not called directly
	// The CRUD endpoint handles creation with hooks
	callback(nil, nil)
}

// Update updates an existing ActivityLog (server-side stub).
func (a *ActivityLogsAPI) Update(id uint, data map[string]interface{}, callback func(*dto.ActivityLogList, error)) {
	// Server-side: this is typically not called directly
	callback(nil, nil)
}

// Delete deletes a ActivityLog by ID (server-side stub).
func (a *ActivityLogsAPI) Delete(id uint, callback func(error)) {
	// Server-side: this is typically not called directly
	callback(nil)
}

