//go:build js && wasm

// Code generated by gux; DO NOT EDIT.
// WASM client - makes HTTP requests to server API.
package api

import (
	"encoding/json"

	"github.com/dougbarrett/gux/examples/admin/dto"
	"github.com/dougbarrett/gux/fetch"
)

// Init is a no-op on client side.
func Init(database interface{}) {}

// UsersAPI provides CRUD operations for User via HTTP.
type UsersAPI struct{}

// Users is the API client for User operations.
var Users = &UsersAPI{}

// List fetches all User records from the server.
func (a *UsersAPI) List(callback func([]dto.UserList, error)) {
	fetch.Get("/__gux_api/crud/users", func(data []byte, err error) {
		if err != nil {
			callback(nil, err)
			return
		}
		var result []dto.UserList
		if err := json.Unmarshal(data, &result); err != nil {
			callback(nil, err)
			return
		}
		callback(result, nil)
	})
}

// Get fetches a single User by ID from the server.
func (a *UsersAPI) Get(id uint, callback func(*dto.UserDetail, error)) {
	fetch.Get(fetch.Sprintf("/__gux_api/crud/users/%d", id), func(data []byte, err error) {
		if err != nil {
			callback(nil, err)
			return
		}
		var result dto.UserDetail
		if err := json.Unmarshal(data, &result); err != nil {
			callback(nil, err)
			return
		}
		callback(&result, nil)
	})
}

// Create creates a new User on the server.
func (a *UsersAPI) Create(data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	body, _ := json.Marshal(data)
	fetch.Post("/__gux_api/crud/users", body, func(data []byte, err error) {
		if err != nil {
			callback(nil, err)
			return
		}
		var result dto.UserDetail
		if err := json.Unmarshal(data, &result); err != nil {
			callback(nil, err)
			return
		}
		callback(&result, nil)
	})
}

// Update updates an existing User on the server.
func (a *UsersAPI) Update(id uint, data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	body, _ := json.Marshal(data)
	fetch.Put(fetch.Sprintf("/__gux_api/crud/users/%d", id), body, func(data []byte, err error) {
		if err != nil {
			callback(nil, err)
			return
		}
		var result dto.UserDetail
		if err := json.Unmarshal(data, &result); err != nil {
			callback(nil, err)
			return
		}
		callback(&result, nil)
	})
}

// Delete deletes a User by ID on the server.
func (a *UsersAPI) Delete(id uint, callback func(error)) {
	fetch.Delete(fetch.Sprintf("/__gux_api/crud/users/%d", id), func(data []byte, err error) {
		callback(err)
	})
}

// ActivityLogsAPI provides CRUD operations for ActivityLog via HTTP.
type ActivityLogsAPI struct{}

// ActivityLogs is the API client for ActivityLog operations.
var ActivityLogs = &ActivityLogsAPI{}

// List fetches all ActivityLog records from the server.
func (a *ActivityLogsAPI) List(callback func([]dto.ActivityLogList, error)) {
	fetch.Get("/__gux_api/crud/activitylogs", func(data []byte, err error) {
		if err != nil {
			callback(nil, err)
			return
		}
		var result []dto.ActivityLogList
		if err := json.Unmarshal(data, &result); err != nil {
			callback(nil, err)
			return
		}
		callback(result, nil)
	})
}

// Get fetches a single ActivityLog by ID from the server.
func (a *ActivityLogsAPI) Get(id uint, callback func(*dto.ActivityLogList, error)) {
	fetch.Get(fetch.Sprintf("/__gux_api/crud/activitylogs/%d", id), func(data []byte, err error) {
		if err != nil {
			callback(nil, err)
			return
		}
		var result dto.ActivityLogList
		if err := json.Unmarshal(data, &result); err != nil {
			callback(nil, err)
			return
		}
		callback(&result, nil)
	})
}
