package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ModelGenTemplates contains the templates for generating model-related code
var ModelGenTemplates = struct {
	Model       string
	DTOList     string
	DTODetail   string
	DTOBrief    string
	AdminList   string
	AdminNew    string
	AdminDetail string
	AdminEdit   string
}{
	Model: `// Code generated by gux model; DO NOT EDIT.
package models

import (
	"gorm.io/gorm"
{{- if .HasTime}}
	"time"
{{- end}}
{{- if .HasJSON}}
	"database/sql/driver"
	"encoding/json"
{{- end}}
)

// {{.Name}} is a GORM model.
type {{.Name}} struct {
	gorm.Model
{{range .Sections}}
	// {{.Name}}
{{range .Fields}}	{{.Name}} {{.GoType}} {{.GormTag}}
{{if .RelationType}}	{{.Preload}} {{.RelationType}}
{{end}}{{end}}{{end}}
}
{{if .HasJSON}}
// StringList is a []string that serializes to JSON in the database
type StringList []string

func (s *StringList) Scan(value any) error {
	if value == nil {
		*s = []string{}
		return nil
	}
	return json.Unmarshal(value.([]byte), s)
}

func (s StringList) Value() (driver.Value, error) {
	return json.Marshal(s)
}
{{end}}`,

	DTOList: `// Code generated by gux model; DO NOT EDIT.
package dto

{{if .HasTime}}import "time"

{{end}}// {{.Name}}List is the DTO for {{.NameLower}} list responses.
type {{.Name}}List struct {
	ID uint ` + "`" + `json:"id" gux:"{{.Name}}.ID"` + "`" + `
{{range .TableFields}}	{{.Name}} {{.DTOType}} ` + "`" + `json:"{{.JSONName}}" gux:"{{$.Name}}.{{.Name}}"{{if .Preload}} preload:"{{.Preload}}"{{end}}` + "`" + `
{{end}}}
`,

	DTODetail: `// {{.Name}}Detail is the DTO for single {{.NameLower}} responses.
type {{.Name}}Detail struct {
	ID uint ` + "`" + `json:"id" gux:"{{.Name}}.ID"` + "`" + `
{{range .AllFields}}	{{.Name}} {{.DTOType}} ` + "`" + `json:"{{.JSONName}}" gux:"{{$.Name}}.{{.Name}}"{{if .Preload}} preload:"{{.Preload}}"{{end}}` + "`" + `
{{end}}	CreatedAt time.Time ` + "`" + `json:"created_at" gux:"{{.Name}}.CreatedAt"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at" gux:"{{.Name}}.UpdatedAt"` + "`" + `
}
`,

	DTOBrief: `// {{.Name}}Brief is a simplified {{.NameLower}} DTO for embedding.
type {{.Name}}Brief struct {
	ID   uint   ` + "`" + `json:"id" gux:"{{.Name}}.ID"` + "`" + `
	Name string ` + "`" + `json:"name" gux:"{{.Name}}.{{.DisplayField}}"` + "`" + `
}
`,

	AdminList: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
{{- if .HasTime}}
	"time"
{{- end}}

	"github.com/dougbarrett/gux/core"
{{- if .AdminEnabled}}
	"github.com/dougbarrett/gux/ui"
{{- end}}
	"{{.ModulePath}}/guxgen/api"
	"{{.ModulePath}}/dto"
)

// {{.NamePlural}} is the admin {{.NamePluralLower}} list page.
func {{.NamePlural}}(r *core.Router) func() core.Node {
	var items []dto.{{.Name}}List

	r.OnLoad(func() {
		api.{{.NamePlural}}.List(func(result []dto.{{.Name}}List, err error) {
			if err == nil {
				items = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		itemsJSON, _ := json.Marshal(items)
		itemsState := r.StateString("items", string(itemsJSON))

		// Parse from state
		var displayItems []dto.{{.Name}}List
		json.Unmarshal([]byte(itemsState.Get()), &displayItems)

{{- if .AdminEnabled}}
		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "{{.NamePlural}}"},
				},
				Title: "{{.NamePlural}}",
				Actions: []core.Node{
					ui.Button(ui.ButtonProps{
						Variant:  ui.ButtonPrimary,
						Children: []core.Node{core.Text("+ Add {{.Name}}")},
						OnClick:  func() { r.Navigate("/admin/{{.RoutePlural}}/new") },
					}),
				},
			}),
			ui.Card(ui.CardProps{
				Children: []core.Node{
					core.Table(core.Class("w-full"),
						core.Thead(core.Class("bg-gray-100 dark:bg-gray-700"),
							core.Tr(core.Attrs{},
								{{.Name}}TableHeaders()...,
							),
						),
						core.Tbody(core.Attrs{},
							{{.Name}}TableRows(displayItems, r)...,
						),
					),
				},
			}),
		)
{{- else}}
		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-6xl mx-auto px-4 py-8"),
				core.H1(core.Class("text-3xl font-bold text-white mb-8"),
					core.Text("{{.NamePlural}}"),
				),

				// Add button
				core.Div(core.Class("mb-4"),
					core.A(
						core.Attrs{Href: "/admin/{{.RoutePlural}}/new", Class: "inline-flex items-center px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition"},
						core.Text("+ Add {{.Name}}"),
					),
				),

				// Table
				core.Div(core.Class("bg-gray-800 rounded-lg overflow-hidden"),
					core.Table(core.Class("w-full"),
						core.Thead(core.Class("bg-gray-700"),
							core.Tr(core.Attrs{},
								{{.Name}}TableHeaders()...,
							),
						),
						core.Tbody(core.Attrs{},
							{{.Name}}TableRows(displayItems, r)...,
						),
					),
				),
			),
		)
{{- end}}
	}
}

func {{.Name}}TableHeaders() []core.Node {
	return []core.Node{
		tableHeader{{.Name}}("ID"),
{{range .TableFields}}		tableHeader{{$.Name}}("{{.Label}}"),
{{end}}		tableHeader{{$.Name}}("Actions"),
	}
}

func tableHeader{{.Name}}(text string) core.Node {
{{- if .AdminEnabled}}
	return core.Th(core.Class("px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"),
		core.Text(text),
	)
{{- else}}
	return core.Th(core.Class("px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"),
		core.Text(text),
	)
{{- end}}
}

func {{.Name}}TableRows(items []dto.{{.Name}}List, r *core.Router) []core.Node {
	if len(items) == 0 {
		return []core.Node{
			core.Tr(core.Attrs{},
{{- if .AdminEnabled}}
				core.Td(core.Class("px-6 py-4 text-gray-500 dark:text-gray-400 text-center"),
					core.Text("No {{.NamePluralLower}} found"),
				),
{{- else}}
				core.Td(core.Class("px-6 py-4 text-gray-400 text-center"),
					core.Text("No {{.NamePluralLower}} found"),
				),
{{- end}}
			),
		}
	}

	var rows []core.Node
	for _, item := range items {
{{- if .AdminEnabled}}
		rows = append(rows, core.Tr(core.Class("border-t border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-750"),
			tableCell{{.Name}}(fmt.Sprintf("%d", item.ID)),
{{range .TableFields}}			{{$.Name}}Cell{{.Name}}(item),
{{end}}			{{.Name}}ActionsCell(item.ID, r),
		))
{{- else}}
		rows = append(rows, core.Tr(core.Class("border-t border-gray-700 hover:bg-gray-750"),
			tableCell{{.Name}}(fmt.Sprintf("%d", item.ID)),
{{range .TableFields}}			{{$.Name}}Cell{{.Name}}(item),
{{end}}			{{.Name}}ActionsCell(item.ID, r),
		))
{{- end}}
	}
	return rows
}

func tableCell{{.Name}}(text string) core.Node {
{{- if .AdminEnabled}}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm text-gray-700 dark:text-gray-300"),
		core.Text(text),
	)
{{- else}}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm text-gray-300"),
		core.Text(text),
	)
{{- end}}
}

func {{.Name}}ActionsCell(id uint, r *core.Router) core.Node {
{{- if .AdminEnabled}}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm"),
		ui.Button(ui.ButtonProps{
			Variant:  ui.ButtonGhost,
			Size:     ui.ButtonSM,
			Children: []core.Node{core.Text("View")},
			OnClick:  func() { r.Navigate(fmt.Sprintf("/admin/{{.RoutePlural}}/%d", id)) },
		}),
	)
{{- else}}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm"),
		core.A(
			core.Attrs{Href: fmt.Sprintf("/admin/{{.RoutePlural}}/%d", id), Class: "text-blue-400 hover:text-blue-300 mr-3"},
			core.Text("View"),
		),
	)
{{- end}}
}

{{range .TableFields}}
func {{$.Name}}Cell{{.Name}}(item dto.{{$.Name}}List) core.Node {
{{- if .IsRelation}}
	text := "-"
	if item.{{.DTOFieldName}} != nil {
		text = item.{{.DTOFieldName}}.Name
	}
	return tableCell{{$.Name}}(text)
{{- else if .IsBool}}
	{{- if .Badge}}
	variant := "{{.Badge.FalseVariant}}"
	label := "{{.Badge.FalseLabel}}"
	if item.{{.DTOFieldName}} {
		variant = "{{.Badge.TrueVariant}}"
		label = "{{.Badge.TrueLabel}}"
	}
	colorClass := "bg-gray-600"
	if variant == "success" {
		colorClass = "bg-green-600"
	} else if variant == "secondary" {
		colorClass = "bg-gray-600"
	}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap"),
		core.Span(core.Class("px-2 py-1 text-xs font-medium rounded "+colorClass+" text-white"),
			core.Text(label),
		),
	)
	{{- else}}
	text := "No"
	if item.{{.DTOFieldName}} {
		text = "Yes"
	}
	return tableCell{{$.Name}}(text)
	{{- end}}
{{- else if .IsTime}}
	return tableCell{{$.Name}}(item.{{.DTOFieldName}}.Format("Jan 2, 2006"))
{{- else}}
	return tableCell{{$.Name}}({{if eq .Type "int" "uint" "float64"}}fmt.Sprintf("%v", item.{{.DTOFieldName}}){{else}}item.{{.DTOFieldName}}{{end}})
{{- end}}
}
{{end}}
{{if .HasTime}}
func format{{.Name}}Time(t time.Time) string {
	return t.Format("Jan 2, 2006")
}
{{end}}
{{- if not .AdminEnabled}}
// Nav renders the admin navigation header.
func Nav() core.Node {
	return core.Div(core.Class("bg-gray-800 border-b border-gray-700"),
		core.Div(core.Class("max-w-6xl mx-auto px-4 py-4"),
			core.A(
				core.Attrs{Href: "/admin", Class: "text-xl font-bold text-white hover:text-gray-300"},
				core.Text("Admin"),
			),
		),
	)
}
{{- end}}
`,

	AdminNew: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
{{- if .HasRelations}}
	"encoding/json"
	"fmt"
{{- end}}
	"strconv"

	"github.com/dougbarrett/gux/core"
{{- if .AdminEnabled}}
	"github.com/dougbarrett/gux/ui"
{{- end}}
	"{{.ModulePath}}/guxgen/api"
	"{{.ModulePath}}/dto"
)

// {{.Name}}New is the form for creating a new {{.NameLower}}.
func {{.Name}}New(r *core.Router) func() core.Node {
{{- range .Relations}}
	var {{.VarName}} []dto.{{.Model}}List
{{- end}}

	r.OnLoad(func() {
{{- range .Relations}}
		api.{{.ModelPlural}}.List(func(result []dto.{{.Model}}List, err error) {
			if err == nil {
				{{.VarName}} = result
			}
		})
{{- end}}
	})

	return func() core.Node {
		// Form state
{{range .AllFields}}		{{.StateVar}} := r.State{{.StateType}}("{{.StateName}}", {{.StateDefault}})
{{end}}		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")

{{- range .Relations}}
		// {{.Label}} state
		{{.VarName}}JSON, _ := json.Marshal({{.VarName}})
		{{.VarName}}State := r.StateString("{{.VarName}}", string({{.VarName}}JSON))
		var {{.VarName}}Options []dto.{{.Model}}List
		json.Unmarshal([]byte({{.VarName}}State.Get()), &{{.VarName}}Options)
{{- end}}

{{- if .AdminEnabled}}
		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertSuccess,
				Message: successState.Get(),
			})
		} else if errorState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}
{{- else}}
		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-green-900 border border-green-700 rounded-lg text-green-300"),
				core.Text(successState.Get()),
			)
		} else if errorState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-red-900 border border-red-700 rounded-lg text-red-300"),
				core.Text(errorState.Get()),
			)
		}
{{- end}}

		save := func() {
			// Validate required fields
{{range .RequiredFields}}			if {{.StateVar}}.Get() == {{.EmptyValue}} {
				errorState.Set("{{.Label}} is required")
				return
			}
{{end}}
			data := map[string]any{
{{range .AllFields}}				"{{.JSONName}}": {{.DataValue}},
{{end}}			}

			api.{{.NamePlural}}.Create(data, func(result *dto.{{.Name}}Detail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("{{.Name}} created successfully!")
					r.Navigate("/admin/{{.RoutePlural}}")
				}
			})
		}

{{- if .AdminEnabled}}
		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "{{.NamePlural}}", Href: "/admin/{{.RoutePlural}}"},
					{Label: "Create New"},
				},
				Title: "Create New {{.Name}}",
			}),
			messageNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{
{{range $sectionName, $fields := .SectionedFields}}
							// {{$sectionName}}
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("{{$sectionName}}"),
								),
{{range $fields}}{{.FormField}}{{end}}							),
{{end}}
							// Submit
							ui.Button(ui.ButtonProps{
								Variant:  ui.ButtonPrimary,
								Class:    "w-full",
								OnClick:  save,
								Children: []core.Node{core.Text("Create {{.Name}}")},
							}),
						},
					}),
				},
			}),
		)
{{- else}}
		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: "/admin/{{.RoutePlural}}", Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to {{.NamePlural}}"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text("Create New {{.Name}}"),
				),

				messageNode,

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),
{{range $sectionName, $fields := .SectionedFields}}
					// {{$sectionName}}
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("{{$sectionName}}"),
						),
{{range $fields}}{{.FormField}}{{end}}					),
{{end}}
					// Submit
					core.Button(
						core.Attrs{
							Type:    "button",
							Class:   "w-full px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition",
							OnClick: save,
						},
						core.Text("Create {{.Name}}"),
					),
				),
			),
		)
{{- end}}
	}
}

func {{.NameLower}}FormField(label, inputType, name, value string, onChange func(string), onEnter ...func()) core.Node {
{{- if .AdminEnabled}}
	attrs := core.Attrs{
		Type:     inputType,
		Name:     name,
		Value:    value,
		Class:    "w-full px-4 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white focus:outline-none focus:border-blue-500",
		OnChange: onChange,
	}
	if len(onEnter) > 0 {
		attrs.OnEnter = onEnter[0]
	}
	return core.Div(core.Class("mb-4"),
		core.Label(core.Class("block text-gray-700 dark:text-gray-300 text-sm font-medium mb-2"),
			core.Text(label),
		),
		core.Input(attrs),
	)
{{- else}}
	attrs := core.Attrs{
		Type:     inputType,
		Name:     name,
		Value:    value,
		Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
		OnChange: onChange,
	}
	if len(onEnter) > 0 {
		attrs.OnEnter = onEnter[0]
	}
	return core.Div(core.Class("mb-4"),
		core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
			core.Text(label),
		),
		core.Input(attrs),
	)
{{- end}}
}

func parseUint(s string) uint {
	if s == "" {
		return 0
	}
	v, _ := strconv.ParseUint(s, 10, 64)
	return uint(v)
}

func parseUintPtr(s string) *uint {
	if s == "" {
		return nil
	}
	v, _ := strconv.ParseUint(s, 10, 64)
	u := uint(v)
	return &u
}
`,

	AdminDetail: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/dougbarrett/gux/core"
{{- if .AdminEnabled}}
	"github.com/dougbarrett/gux/ui"
{{- end}}
	"{{.ModulePath}}/guxgen/api"
	"{{.ModulePath}}/dto"
)

// {{.Name}}Detail shows a single {{.NameLower}}.
func {{.Name}}Detail(r *core.Router) func() core.Node {
	var item *dto.{{.Name}}Detail

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.{{.NamePlural}}.Get(uint(id), func(result *dto.{{.Name}}Detail, err error) {
			if err == nil {
				item = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.{{.Name}}Detail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.{{.Name}}Detail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)

{{- if .AdminEnabled}}
		// Delete confirmation state
		confirmDelete := r.StateBool("confirm_delete", false)
		errorState := r.StateString("error", "")

		if displayItem.ID == 0 {
			return core.Frag(
				ui.PageHeader(ui.PageHeaderProps{
					Breadcrumbs: []ui.BreadcrumbItem{
						{Label: "Admin", Href: "/admin"},
						{Label: "{{.NamePlural}}", Href: "/admin/{{.RoutePlural}}"},
						{Label: "Not Found"},
					},
					Title: "{{.Name}} Not Found",
				}),
				ui.Alert(ui.AlertProps{
					Variant: ui.AlertError,
					Message: "The requested {{.NameLower}} could not be found.",
				}),
			)
		}

		// Build display name from display field
		displayName := {{if .DisplayField}}displayItem.{{.DisplayField}}{{else}}""{{end}}
		if displayName == "" {
			displayName = fmt.Sprintf("{{.Name}} #%d", displayItem.ID)
		}

		// Delete handler
		handleDelete := func() {
			if confirmDelete.Get() {
				api.{{.NamePlural}}.Delete(displayItem.ID, func(err error) {
					if err != nil {
						errorState.Set(err.Error())
						confirmDelete.Set(false)
					} else {
						r.Navigate("/admin/{{.RoutePlural}}")
					}
				})
			} else {
				confirmDelete.Set(true)
			}
		}

		// Build action buttons
		var actions []core.Node
		if confirmDelete.Get() {
			actions = []core.Node{
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonGhost,
					Children: []core.Node{core.Text("Cancel")},
					OnClick:  func() { confirmDelete.Set(false) },
				}),
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonDestructive,
					Children: []core.Node{core.Text("Confirm Delete")},
					OnClick:  handleDelete,
				}),
			}
		} else {
			actions = []core.Node{
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonPrimary,
					Children: []core.Node{core.Text("Edit")},
					OnClick:  func() { r.Navigate(fmt.Sprintf("/admin/{{.RoutePlural}}/%d/edit", displayItem.ID)) },
				}),
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonDestructive,
					Children: []core.Node{core.Text("Delete")},
					OnClick:  handleDelete,
				}),
			}
		}

		var errorNode core.Node = core.Frag()
		if errorState.Get() != "" {
			errorNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}

		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "{{.NamePlural}}", Href: "/admin/{{.RoutePlural}}"},
					{Label: displayName},
				},
				Title:   displayName,
				Actions: actions,
			}),
			errorNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{
{{range $sectionName, $fields := .SectionedFields}}
							// {{$sectionName}}
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("{{$sectionName}}"),
								),
{{range $fields}}{{.DetailField}}{{end}}							),
{{end}}
							// Timestamps
							core.Div(core.Class("mt-6 pt-4 border-t border-gray-200 dark:border-gray-700"),
								{{.NameLower}}DetailRow("Created", displayItem.CreatedAt.Format("Jan 2, 2006 3:04 PM")),
								{{.NameLower}}DetailRow("Updated", displayItem.UpdatedAt.Format("Jan 2, 2006 3:04 PM")),
							),
						},
					}),
				},
			}),
		)
{{- else}}
		if displayItem.ID == 0 {
			return core.Div(core.Class("min-h-screen bg-gray-900"),
				Nav(),
				core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
					core.Text("{{.Name}} not found"),
				),
			)
		}

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: "/admin/{{.RoutePlural}}", Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to {{.NamePlural}}"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text(fmt.Sprintf("{{.Name}} #%d", displayItem.ID)),
				),

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),
{{range $sectionName, $fields := .SectionedFields}}
					// {{$sectionName}}
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("{{$sectionName}}"),
						),
{{range $fields}}{{.DetailField}}{{end}}					),
{{end}}
					// Timestamps
					core.Div(core.Class("mt-6 pt-4 border-t border-gray-700"),
						{{.NameLower}}DetailRow("Created", displayItem.CreatedAt.Format("Jan 2, 2006 3:04 PM")),
						{{.NameLower}}DetailRow("Updated", displayItem.UpdatedAt.Format("Jan 2, 2006 3:04 PM")),
					),
				),
			),
		)
{{- end}}
	}
}

func {{.NameLower}}DetailRow(label, value string) core.Node {
{{- if .AdminEnabled}}
	return core.Div(core.Class("flex py-2"),
		core.Div(core.Class("w-1/3 text-gray-500 dark:text-gray-400"),
			core.Text(label),
		),
		core.Div(core.Class("w-2/3 text-gray-900 dark:text-white"),
			core.Text(value),
		),
	)
{{- else}}
	return core.Div(core.Class("flex py-2"),
		core.Div(core.Class("w-1/3 text-gray-400"),
			core.Text(label),
		),
		core.Div(core.Class("w-2/3 text-white"),
			core.Text(value),
		),
	)
{{- end}}
}
`,

	AdminEdit: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/dougbarrett/gux/core"
{{- if .AdminEnabled}}
	"github.com/dougbarrett/gux/ui"
{{- end}}
	"{{.ModulePath}}/guxgen/api"
	"{{.ModulePath}}/dto"
)

// {{.Name}}Edit is the form for editing an existing {{.NameLower}}.
func {{.Name}}Edit(r *core.Router) func() core.Node {
	var item *dto.{{.Name}}Detail
{{- range .Relations}}
	var {{.VarName}} []dto.{{.Model}}List
{{- end}}

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.{{.NamePlural}}.Get(uint(id), func(result *dto.{{.Name}}Detail, err error) {
			if err == nil {
				item = result
			}
		})
{{- range .Relations}}
		api.{{.ModelPlural}}.List(func(result []dto.{{.Model}}List, err error) {
			if err == nil {
				{{.VarName}} = result
			}
		})
{{- end}}
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.{{.Name}}Detail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.{{.Name}}Detail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)

{{- range .Relations}}
		// {{.Label}} state
		{{.VarName}}JSON, _ := json.Marshal({{.VarName}})
		{{.VarName}}State := r.StateString("{{.VarName}}", string({{.VarName}}JSON))
		var {{.VarName}}Options []dto.{{.Model}}List
		json.Unmarshal([]byte({{.VarName}}State.Get()), &{{.VarName}}Options)
{{- end}}

{{- if .AdminEnabled}}
		if displayItem.ID == 0 {
			return core.Frag(
				ui.PageHeader(ui.PageHeaderProps{
					Breadcrumbs: []ui.BreadcrumbItem{
						{Label: "Admin", Href: "/admin"},
						{Label: "{{.NamePlural}}", Href: "/admin/{{.RoutePlural}}"},
						{Label: "Not Found"},
					},
					Title: "{{.Name}} Not Found",
				}),
				ui.Alert(ui.AlertProps{
					Variant: ui.AlertError,
					Message: "The requested {{.NameLower}} could not be found.",
				}),
			)
		}

		// Build display name from display field
		displayName := {{if .DisplayField}}displayItem.{{.DisplayField}}{{else}}""{{end}}
		if displayName == "" {
			displayName = fmt.Sprintf("{{.Name}} #%d", displayItem.ID)
		}

		// Form state - initialize with current values
{{range .AllFields}}		{{.StateVar}} := r.State{{.StateType}}("{{.StateName}}", {{.EditStateInit}})
{{end}}		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")

		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertSuccess,
				Message: successState.Get(),
			})
		} else if errorState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}

		save := func() {
			// Validate required fields
{{range .RequiredFields}}			if {{.StateVar}}.Get() == {{.EmptyValue}} {
				errorState.Set("{{.Label}} is required")
				return
			}
{{end}}
			data := map[string]any{
{{range .AllFields}}				"{{.JSONName}}": {{.DataValue}},
{{end}}			}

			api.{{.NamePlural}}.Update(displayItem.ID, data, func(result *dto.{{.Name}}Detail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("{{.Name}} updated successfully!")
					r.Navigate(fmt.Sprintf("/admin/{{.RoutePlural}}/%d", displayItem.ID))
				}
			})
		}

		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "{{.NamePlural}}", Href: "/admin/{{.RoutePlural}}"},
					{Label: displayName, Href: fmt.Sprintf("/admin/{{.RoutePlural}}/%d", displayItem.ID)},
					{Label: "Edit"},
				},
				Title: fmt.Sprintf("Edit %s", displayName),
			}),
			messageNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{
{{range $sectionName, $fields := .SectionedFields}}
							// {{$sectionName}}
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("{{$sectionName}}"),
								),
{{range $fields}}{{.FormField}}{{end}}							),
{{end}}
							// Submit
							ui.Button(ui.ButtonProps{
								Variant:  ui.ButtonPrimary,
								Class:    "w-full",
								OnClick:  save,
								Children: []core.Node{core.Text("Save Changes")},
							}),
						},
					}),
				},
			}),
		)
{{- else}}
		if displayItem.ID == 0 {
			return core.Div(core.Class("min-h-screen bg-gray-900"),
				Nav(),
				core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
					core.Text("{{.Name}} not found"),
				),
			)
		}

		// Form state - initialize with current values
{{range .AllFields}}		{{.StateVar}} := r.State{{.StateType}}("{{.StateName}}", {{.EditStateInit}})
{{end}}		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")

		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-green-900 border border-green-700 rounded-lg text-green-300"),
				core.Text(successState.Get()),
			)
		} else if errorState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-red-900 border border-red-700 rounded-lg text-red-300"),
				core.Text(errorState.Get()),
			)
		}

		save := func() {
			// Validate required fields
{{range .RequiredFields}}			if {{.StateVar}}.Get() == {{.EmptyValue}} {
				errorState.Set("{{.Label}} is required")
				return
			}
{{end}}
			data := map[string]any{
{{range .AllFields}}				"{{.JSONName}}": {{.DataValue}},
{{end}}			}

			api.{{.NamePlural}}.Update(displayItem.ID, data, func(result *dto.{{.Name}}Detail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("{{.Name}} updated successfully!")
					r.Navigate(fmt.Sprintf("/admin/{{.RoutePlural}}/%d", displayItem.ID))
				}
			})
		}

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: fmt.Sprintf("/admin/{{.RoutePlural}}/%d", displayItem.ID), Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to {{.Name}}"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text(fmt.Sprintf("Edit {{.Name}} #%d", displayItem.ID)),
				),

				messageNode,

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),
{{range $sectionName, $fields := .SectionedFields}}
					// {{$sectionName}}
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("{{$sectionName}}"),
						),
{{range $fields}}{{.FormField}}{{end}}					),
{{end}}
					// Submit
					core.Button(
						core.Attrs{
							Type:    "button",
							Class:   "w-full px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition",
							OnClick: save,
						},
						core.Text("Save Changes"),
					),
				),
			),
		)
{{- end}}
	}
}
`,
}

// TemplateField represents a field for template rendering
type TemplateField struct {
	Name          string
	Type          string
	GoType        string
	DTOType       string
	DTOFieldName  string // Name of field in DTO (uses Preload name for relations)
	RelationType  string // GORM relation model type (e.g., "User" for FK relation)
	JSONName      string
	Label         string
	GormTag       string
	StateVar      string
	StateType     string
	StateName     string
	StateDefault  string
	EditStateInit string // Initial state value for edit form (reads from displayItem)
	DataValue     string
	EmptyValue    string
	FormField     string
	DetailField   string
	Preload       string
	IsRelation    bool
	IsBool        bool
	IsTime        bool
	IsSlice       bool
	Badge         *BadgeConfig
}

// TemplateSection represents a section for template rendering
type TemplateSection struct {
	Name   string
	Fields []TemplateField
}

// TemplateRelation represents a relation for template rendering
type TemplateRelation struct {
	VarName     string
	Model       string
	ModelPlural string
	Label       string
}

// ModelTemplateData holds all data for model template rendering
type ModelTemplateData struct {
	Name            string
	NameLower       string
	NamePlural      string
	NamePluralLower string
	RoutePlural     string
	ModulePath      string
	Sections        []TemplateSection
	TableFields     []TemplateField
	AllFields       []TemplateField
	RequiredFields  []TemplateField
	Relations       []TemplateRelation
	SectionedFields map[string][]TemplateField
	HasTime         bool
	HasJSON         bool
	HasRelations    bool
	DisplayField    string
	AdminEnabled    bool // From config.Admin - use ui components instead of inline styles
}

// GenerateModelFilesImpl generates all files for a model definition
func GenerateModelFilesImpl(model *ModelDefinition, optionSets map[string]OptionSet, modulePath string, adminEnabled bool) error {
	// Prepare template data
	data := prepareModelTemplateData(model, modulePath)
	data.AdminEnabled = adminEnabled

	// Create directories if needed
	dirs := []string{"models", "dto", "admin"}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("create directory %s: %w", dir, err)
		}
	}

	// Check if non-generated model file exists
	manualModelPath := filepath.Join("models", ToSnakeCase(model.Name)+".go")
	if _, err := os.Stat(manualModelPath); err == nil {
		fmt.Printf("  Skipping model (manual file exists: %s)\n", manualModelPath)
	} else {
		// Generate model file
		modelPath := filepath.Join("models", ToSnakeCase(model.Name)+"_gen.go")
		if err := executeTemplate(ModelGenTemplates.Model, modelPath, data); err != nil {
			return fmt.Errorf("generate model: %w", err)
		}
		fmt.Printf("  %s\n", modelPath)
	}

	// Check if non-generated DTO file exists
	manualDTOPath := filepath.Join("dto", ToSnakeCase(model.Name)+".go")
	if _, err := os.Stat(manualDTOPath); err == nil {
		fmt.Printf("  Skipping DTO (manual file exists: %s)\n", manualDTOPath)
	} else {
		// Generate DTO file
		dtoPath := filepath.Join("dto", ToSnakeCase(model.Name)+"_gen.go")
		if err := generateDTOFile(dtoPath, data); err != nil {
			return fmt.Errorf("generate dto: %w", err)
		}
		fmt.Printf("  %s\n", dtoPath)
	}

	// Generate admin pages
	adminListPath := filepath.Join("admin", ToSnakeCase(model.Name)+"_list_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminList, adminListPath, data); err != nil {
		return fmt.Errorf("generate admin list: %w", err)
	}
	fmt.Printf("  %s\n", adminListPath)

	adminNewPath := filepath.Join("admin", ToSnakeCase(model.Name)+"_new_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminNew, adminNewPath, data); err != nil {
		return fmt.Errorf("generate admin new: %w", err)
	}
	fmt.Printf("  %s\n", adminNewPath)

	adminDetailPath := filepath.Join("admin", ToSnakeCase(model.Name)+"_detail_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminDetail, adminDetailPath, data); err != nil {
		return fmt.Errorf("generate admin detail: %w", err)
	}
	fmt.Printf("  %s\n", adminDetailPath)

	adminEditPath := filepath.Join("admin", ToSnakeCase(model.Name)+"_edit_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminEdit, adminEditPath, data); err != nil {
		return fmt.Errorf("generate admin edit: %w", err)
	}
	fmt.Printf("  %s\n", adminEditPath)

	return nil
}

// detectDisplayField auto-detects the best field to use for display name
// Priority: Name > Title > FirstName > Label > first string field
func detectDisplayField(model *ModelDefinition) string {
	candidates := []string{"Name", "Title", "FirstName", "Label"}

	// Check for candidate fields
	for _, candidate := range candidates {
		for _, fields := range model.Sections {
			for _, f := range fields {
				if f.Name == candidate && f.Type == "string" {
					return candidate
				}
			}
		}
	}

	// Fallback to first string field
	for _, fields := range model.Sections {
		for _, f := range fields {
			if f.Type == "string" {
				return f.Name
			}
		}
	}

	return "" // Will use ID as fallback in template
}

func prepareModelTemplateData(model *ModelDefinition, modulePath string) *ModelTemplateData {
	data := &ModelTemplateData{
		Name:            model.Name,
		NameLower:       strings.ToLower(model.Name),
		NamePlural:      ToPlural(model.Name),
		NamePluralLower: strings.ToLower(ToPlural(model.Name)),
		RoutePlural:     ToKebabCase(ToPlural(model.Name)),
		ModulePath:      modulePath,
		SectionedFields: make(map[string][]TemplateField),
		DisplayField:    detectDisplayField(model),
	}

	// Process sections and fields
	for sectionName, fields := range model.Sections {
		var sectionFields []TemplateField

		for _, field := range fields {
			tf := convertToTemplateField(&field, model.Name)
			sectionFields = append(sectionFields, tf)
			data.AllFields = append(data.AllFields, tf)

			if field.Table {
				data.TableFields = append(data.TableFields, tf)
			}

			if field.Required {
				data.RequiredFields = append(data.RequiredFields, tf)
			}

			if field.Relation != "" {
				data.HasRelations = true
				data.Relations = append(data.Relations, TemplateRelation{
					VarName:     strings.ToLower(field.Relation) + "s",
					Model:       field.Relation,
					ModelPlural: ToPlural(field.Relation),
					Label:       getLabel(field),
				})
			}

			if tf.IsTime {
				data.HasTime = true
			}
			if tf.IsSlice && tf.Type == "[]string" {
				data.HasJSON = true
			}
		}

		data.Sections = append(data.Sections, TemplateSection{
			Name:   sectionName,
			Fields: sectionFields,
		})
		data.SectionedFields[sectionName] = sectionFields
	}

	return data
}

func convertToTemplateField(field *ModelField, modelName string) TemplateField {
	tf := TemplateField{
		Name:         field.Name,
		Type:         field.Type,
		GoType:       field.Type,
		DTOType:      field.Type,
		DTOFieldName: field.Name, // Default to Name, overwritten for relations
		JSONName:     ToSnakeCase(field.Name),
		Label:        getLabel(*field),
		IsRelation:   field.Relation != "",
		IsBool:       field.Type == "bool",
		IsTime:       field.Type == "time.Time" || field.Type == "*time.Time",
		IsSlice:      IsSliceType(field.Type),
		Badge:        field.Badge,
	}

	// Generate GORM tag
	tf.GormTag = generateGormTag(field)

	// Generate state helpers
	tf.StateVar = strings.ToLower(field.Name[:1]) + field.Name[1:] + "State"
	tf.StateName = ToSnakeCase(field.Name)

	switch field.Type {
	case "string":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = tf.StateVar + ".Get()"
		tf.EditStateInit = fmt.Sprintf("displayItem.%s", tf.DTOFieldName)
	case "int", "uint":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseUint(%s.Get())", tf.StateVar)
		tf.EditStateInit = fmt.Sprintf("fmt.Sprintf(\"%%d\", displayItem.%s)", tf.DTOFieldName)
	case "*uint":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseUintPtr(%s.Get())", tf.StateVar)
		tf.DTOType = fmt.Sprintf("*%sBrief", field.Relation) // No dto. prefix - same package
		tf.Preload = strings.TrimSuffix(field.Name, "ID")
		tf.DTOFieldName = tf.Preload  // Use preload name for DTO field access
		tf.RelationType = field.Relation // GORM relation model type
		// For FK relations, get the ID from the related object
		preloadName := strings.TrimSuffix(field.Name, "ID")
		tf.EditStateInit = fmt.Sprintf("func() string { if displayItem.%s != nil { return fmt.Sprintf(\"%%d\", displayItem.%s.ID) }; return \"\" }()", preloadName, preloadName)
	case "bool":
		tf.StateType = "Bool"
		tf.StateDefault = "false"
		tf.EmptyValue = "false"
		tf.DataValue = tf.StateVar + ".Get()"
		tf.EditStateInit = fmt.Sprintf("displayItem.%s", tf.DTOFieldName)
	case "time.Time":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseTime(%s.Get())", tf.StateVar)
		tf.EditStateInit = fmt.Sprintf("displayItem.%s.Format(\"2006-01-02\")", tf.DTOFieldName)
	case "*time.Time":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseTimePtr(%s.Get())", tf.StateVar)
		tf.EditStateInit = fmt.Sprintf("func() string { if displayItem.%s != nil { return displayItem.%s.Format(\"2006-01-02\") }; return \"\" }()", tf.DTOFieldName, tf.DTOFieldName)
	case "[]string":
		tf.StateType = "String"
		tf.StateDefault = `"[]"`
		tf.EmptyValue = `"[]"`
		tf.DataValue = fmt.Sprintf("parseStringSlice(%s.Get())", tf.StateVar)
		tf.GoType = "StringList"
		tf.EditStateInit = fmt.Sprintf("func() string { b, _ := json.Marshal(displayItem.%s); return string(b) }()", tf.DTOFieldName)
	default:
		if IsSliceType(field.Type) && field.Relation != "" {
			// M2M relation
			tf.StateType = "String"
			tf.StateDefault = `"[]"`
			tf.DTOType = fmt.Sprintf("[]%sBrief", field.Relation) // No dto. prefix - same package
			tf.Preload = field.Name
			tf.DTOFieldName = field.Name // For M2M, field name is already the preload name
			tf.EditStateInit = `"[]"`    // TODO: Initialize from displayItem for M2M
		}
	}

	// Generate form field code (using model name for function prefix)
	modelNameLower := strings.ToLower(modelName)
	tf.FormField = generateFormFieldCode(field, tf, modelNameLower)

	// Generate detail field code (using model name for function prefix)
	tf.DetailField = generateDetailFieldCode(field, tf, modelNameLower)

	return tf
}

func getLabel(field ModelField) string {
	if field.Label != "" {
		return field.Label
	}
	// Convert PascalCase to Title Case with spaces
	var result strings.Builder
	for i, r := range field.Name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune(' ')
		}
		result.WriteRune(r)
	}
	return result.String()
}

func generateGormTag(field *ModelField) string {
	var tags []string

	if field.Required {
		tags = append(tags, "not null")
	}

	if field.Type == "[]string" {
		tags = append(tags, "type:json")
	}

	if field.Many2Many != "" {
		tags = append(tags, fmt.Sprintf("many2many:%s", field.Many2Many))
	}

	if field.Relation != "" && !IsSliceType(field.Type) {
		// FK field - no special tag needed, GORM handles it
	}

	jsonTag := fmt.Sprintf(`json:"%s"`, ToSnakeCase(field.Name))

	if len(tags) > 0 {
		return fmt.Sprintf("`%s gorm:\"%s\"`", jsonTag, strings.Join(tags, ";"))
	}
	return fmt.Sprintf("`%s`", jsonTag)
}

func generateFormFieldCode(field *ModelField, tf TemplateField, modelNameLower string) string {
	var buf strings.Builder
	indent := "\t\t\t\t\t\t"

	switch {
	case field.Input == "textarea":
		buf.WriteString(fmt.Sprintf(`%score.Div(core.Class("mb-4"),
%s	core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
%s		core.Text("%s"),
%s	),
%s	core.Textarea(core.Attrs{
%s		Name:     "%s",
%s		Value:    %s.Get(),
%s		Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
%s		OnChange: func(v string) { %s.Set(v) },
%s	}),
%s),
`, indent, indent, indent, tf.Label, indent, indent, indent, tf.StateName, indent, tf.StateVar, indent, indent, tf.StateVar, indent, indent))

	case field.Input == "select" || (field.Type == "*uint" && field.Relation != ""):
		// Select dropdown
		buf.WriteString(fmt.Sprintf(`%score.Div(core.Class("mb-4"),
%s	core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
%s		core.Text("%s"),
%s	),
%s	core.Select(
%s		core.Attrs{
%s			Name:  "%s",
%s			Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
%s			OnChange: func(v string) { %s.Set(v) },
%s		},
`, indent, indent, indent, tf.Label, indent, indent, indent, indent, tf.StateName, indent, indent, tf.StateVar, indent))

		if field.Relation != "" {
			// Dynamic options from relation - generate inline by building slice
			varName := strings.ToLower(field.Relation) + "sOptions"
			buf.WriteString(fmt.Sprintf(`%s		func() []core.Node {
%s			opts := []core.Node{core.Option(core.Attrs{Value: ""}, core.Text("Select %s"))}
%s			for _, item := range %s {
%s				idStr := strconv.FormatUint(uint64(item.ID), 10)
%s				attrs := core.Attrs{Value: idStr}
%s				if idStr == %s.Get() {
%s					attrs.Extra = map[string]string{"selected": "selected"}
%s				}
%s				opts = append(opts, core.Option(attrs, core.Text(fmt.Sprintf("#%%d", item.ID))))
%s			}
%s			return opts
%s		}()...,
`, indent, indent, tf.Label, indent, varName, indent, indent, indent, tf.StateVar, indent, indent, indent, indent, indent, indent))
		} else {
			// Static options
			for _, opt := range field.Options {
				buf.WriteString(fmt.Sprintf(`%s		core.Option(core.Attrs{Value: "%s"}, core.Text("%s")),
`, indent, opt.Value, opt.Label))
			}
		}

		buf.WriteString(fmt.Sprintf(`%s	),
%s),
`, indent, indent))

	case field.Type == "bool":
		buf.WriteString(fmt.Sprintf(`%score.Div(core.Class("mb-4 flex items-center"),
%s	core.Input(func() core.Attrs {
%s		attrs := core.Attrs{
%s			Type:    "checkbox",
%s			Name:    "%s",
%s			Class:   "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-600 rounded bg-gray-700",
%s			OnChange: func(v string) { %s.Set(v == "true") },
%s		}
%s		if %s.Get() {
%s			attrs.Extra = map[string]string{"checked": "checked"}
%s		}
%s		return attrs
%s	}()),
%s	core.Label(core.Class("ml-2 block text-gray-300 text-sm"),
%s		core.Text("%s"),
%s	),
%s),
`, indent, indent, indent, indent, indent, tf.StateName, indent, indent, tf.StateVar, indent, indent, tf.StateVar, indent, indent, indent, indent, indent, indent, tf.Label, indent, indent))

	default:
		// Standard input field
		inputType := "text"
		if field.Input != "" {
			inputType = field.Input
		} else if field.Type == "int" || field.Type == "uint" || field.Type == "float64" {
			inputType = "number"
		} else if strings.Contains(strings.ToLower(field.Name), "email") {
			inputType = "email"
		} else if strings.Contains(strings.ToLower(field.Name), "password") {
			inputType = "password"
		}

		buf.WriteString(fmt.Sprintf(`%s%sFormField("%s", "%s", "%s", %s.Get(), func(v string) { %s.Set(v) }, save),
`, indent, modelNameLower, tf.Label, inputType, tf.StateName, tf.StateVar, tf.StateVar))
	}

	return buf.String()
}

func generateDetailFieldCode(field *ModelField, tf TemplateField, modelNameLower string) string {
	indent := "\t\t\t\t\t\t"

	switch {
	case field.Relation != "" && !IsSliceType(field.Type):
		// FK relation - show related name with nil check
		preloadName := strings.TrimSuffix(field.Name, "ID")
		return fmt.Sprintf(`%s%sDetailRow("%s", func() string {
%s	if displayItem.%s != nil {
%s		return displayItem.%s.Name
%s	}
%s	return "-"
%s}()),
`, indent, modelNameLower, tf.Label, indent, preloadName, indent, preloadName, indent, indent, indent)

	case field.Type == "bool":
		return fmt.Sprintf(`%s%sDetailRow("%s", func() string {
%s	if displayItem.%s {
%s		return "Yes"
%s	}
%s	return "No"
%s}()),
`, indent, modelNameLower, tf.Label, indent, tf.DTOFieldName, indent, indent, indent, indent)

	case field.Type == "time.Time" || field.Type == "*time.Time":
		return fmt.Sprintf(`%s%sDetailRow("%s", displayItem.%s.Format("Jan 2, 2006")),
`, indent, modelNameLower, tf.Label, tf.DTOFieldName)

	default:
		if field.Type == "int" || field.Type == "uint" || field.Type == "float64" {
			return fmt.Sprintf(`%s%sDetailRow("%s", fmt.Sprintf("%%v", displayItem.%s)),
`, indent, modelNameLower, tf.Label, tf.DTOFieldName)
		}
		return fmt.Sprintf(`%s%sDetailRow("%s", displayItem.%s),
`, indent, modelNameLower, tf.Label, tf.DTOFieldName)
	}
}

func generateDTOFile(path string, data *ModelTemplateData) error {
	// Check which Brief types already exist in the dto package
	existingTypes := findExistingDTOTypes(filepath.Dir(path))

	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Code generated by gux model; DO NOT EDIT.\npackage dto\n\n")

	// Always import time since Detail DTO includes CreatedAt/UpdatedAt
	buf.WriteString("import \"time\"\n\n")

	// Write List DTO
	buf.WriteString(fmt.Sprintf("// %sList is the DTO for %s list responses.\n", data.Name, data.NameLower))
	buf.WriteString(fmt.Sprintf("type %sList struct {\n", data.Name))
	buf.WriteString(fmt.Sprintf("\tID uint `json:\"id\" gux:\"%s.ID\"`\n", data.Name))
	for _, field := range data.TableFields {
		// For relations, use the preload name as the DTO field name
		dtoFieldName := field.Name
		if field.Preload != "" {
			dtoFieldName = field.Preload
		}
		tag := fmt.Sprintf("`json:\"%s\" gux:\"%s.%s\"", field.JSONName, data.Name, field.Name)
		if field.Preload != "" {
			tag += fmt.Sprintf(" preload:\"%s\"", field.Preload)
		}
		tag += "`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", dtoFieldName, field.DTOType, tag))
	}
	buf.WriteString("}\n\n")

	// Write Detail DTO
	buf.WriteString(fmt.Sprintf("// %sDetail is the DTO for single %s responses.\n", data.Name, data.NameLower))
	buf.WriteString(fmt.Sprintf("type %sDetail struct {\n", data.Name))
	buf.WriteString(fmt.Sprintf("\tID uint `json:\"id\" gux:\"%s.ID\"`\n", data.Name))
	for _, field := range data.AllFields {
		// For relations, use the preload name as the DTO field name
		dtoFieldName := field.Name
		if field.Preload != "" {
			dtoFieldName = field.Preload
		}
		tag := fmt.Sprintf("`json:\"%s\" gux:\"%s.%s\"", field.JSONName, data.Name, field.Name)
		if field.Preload != "" {
			tag += fmt.Sprintf(" preload:\"%s\"", field.Preload)
		}
		tag += "`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", dtoFieldName, field.DTOType, tag))
	}
	buf.WriteString(fmt.Sprintf("\tCreatedAt time.Time `json:\"created_at\" gux:\"%s.CreatedAt\"`\n", data.Name))
	buf.WriteString(fmt.Sprintf("\tUpdatedAt time.Time `json:\"updated_at\" gux:\"%s.UpdatedAt\"`\n", data.Name))
	buf.WriteString("}\n")

	// Write Brief DTOs for relations (only if they don't already exist)
	for _, rel := range data.Relations {
		briefTypeName := rel.Model + "Brief"
		if existingTypes[briefTypeName] {
			continue // Skip - already exists in another file
		}
		buf.WriteString(fmt.Sprintf("\n// %sBrief is a simplified %s DTO for embedding.\n", rel.Model, strings.ToLower(rel.Model)))
		buf.WriteString(fmt.Sprintf("type %sBrief struct {\n", rel.Model))
		buf.WriteString(fmt.Sprintf("\tID   uint   `json:\"id\" gux:\"%s.ID\"`\n", rel.Model))
		buf.WriteString(fmt.Sprintf("\tName string `json:\"name\" gux:\"%s.Name\"`\n", rel.Model))
		buf.WriteString("}\n")
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}

// findExistingDTOTypes scans the dto directory for existing type declarations
func findExistingDTOTypes(dtoDir string) map[string]bool {
	types := make(map[string]bool)

	files, err := os.ReadDir(dtoDir)
	if err != nil {
		return types // Directory may not exist yet
	}

	for _, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".go") {
			continue
		}
		// Skip generated files (we'll regenerate them)
		if strings.HasSuffix(file.Name(), "_gen.go") {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dtoDir, file.Name()))
		if err != nil {
			continue
		}

		// Simple regex to find type declarations
		// Matches: type TypeName struct
		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "type ") && strings.Contains(line, " struct") {
				parts := strings.Fields(line)
				if len(parts) >= 2 {
					types[parts[1]] = true
				}
			}
		}
	}

	return types
}

func executeTemplate(tmplText, path string, data *ModelTemplateData) error {
	tmpl, err := template.New("").Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}
