package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ModelGenTemplates contains the templates for generating model-related code
var ModelGenTemplates = struct {
	Model      string
	DTOList    string
	DTODetail  string
	DTOBrief   string
	AdminList  string
	AdminNew   string
	AdminDetail string
}{
	Model: `// Code generated by gux model; DO NOT EDIT.
package models

import (
	"gorm.io/gorm"
{{- if .HasTime}}
	"time"
{{- end}}
{{- if .HasJSON}}
	"database/sql/driver"
	"encoding/json"
{{- end}}
)

// {{.Name}} is a GORM model.
type {{.Name}} struct {
	gorm.Model
{{range .Sections}}
	// {{.Name}}
{{range .Fields}}	{{.Name}} {{.GoType}} {{.GormTag}}
{{end}}{{end}}
}
{{if .HasJSON}}
// StringList is a []string that serializes to JSON in the database
type StringList []string

func (s *StringList) Scan(value any) error {
	if value == nil {
		*s = []string{}
		return nil
	}
	return json.Unmarshal(value.([]byte), s)
}

func (s StringList) Value() (driver.Value, error) {
	return json.Marshal(s)
}
{{end}}`,

	DTOList: `// Code generated by gux model; DO NOT EDIT.
package dto

{{if .HasTime}}import "time"

{{end}}// {{.Name}}List is the DTO for {{.NameLower}} list responses.
type {{.Name}}List struct {
	ID uint ` + "`" + `json:"id" gux:"{{.Name}}.ID"` + "`" + `
{{range .TableFields}}	{{.Name}} {{.DTOType}} ` + "`" + `json:"{{.JSONName}}" gux:"{{$.Name}}.{{.Name}}"{{if .Preload}} preload:"{{.Preload}}"{{end}}` + "`" + `
{{end}}}
`,

	DTODetail: `// {{.Name}}Detail is the DTO for single {{.NameLower}} responses.
type {{.Name}}Detail struct {
	ID uint ` + "`" + `json:"id" gux:"{{.Name}}.ID"` + "`" + `
{{range .AllFields}}	{{.Name}} {{.DTOType}} ` + "`" + `json:"{{.JSONName}}" gux:"{{$.Name}}.{{.Name}}"{{if .Preload}} preload:"{{.Preload}}"{{end}}` + "`" + `
{{end}}	CreatedAt time.Time ` + "`" + `json:"created_at" gux:"{{.Name}}.CreatedAt"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at" gux:"{{.Name}}.UpdatedAt"` + "`" + `
}
`,

	DTOBrief: `// {{.Name}}Brief is a simplified {{.NameLower}} DTO for embedding.
type {{.Name}}Brief struct {
	ID   uint   ` + "`" + `json:"id" gux:"{{.Name}}.ID"` + "`" + `
	Name string ` + "`" + `json:"name" gux:"{{.Name}}.{{.DisplayField}}"` + "`" + `
}
`,

	AdminList: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
{{- if .HasTime}}
	"time"
{{- end}}

	"github.com/dougbarrett/gux/core"
	"{{.ModulePath}}/.gux/api"
	"{{.ModulePath}}/dto"
)

// {{.NamePlural}} is the admin {{.NamePluralLower}} list page.
func {{.NamePlural}}(r *core.Router) func() core.Node {
	var items []dto.{{.Name}}List

	r.OnLoad(func() {
		api.{{.NamePlural}}.List(func(result []dto.{{.Name}}List, err error) {
			if err == nil {
				items = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		itemsJSON, _ := json.Marshal(items)
		itemsState := r.StateString("items", string(itemsJSON))

		// Parse from state
		var displayItems []dto.{{.Name}}List
		json.Unmarshal([]byte(itemsState.Get()), &displayItems)

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-6xl mx-auto px-4 py-8"),
				core.H1(core.Class("text-3xl font-bold text-white mb-8"),
					core.Text("{{.NamePlural}}"),
				),

				// Add button
				core.Div(core.Class("mb-4"),
					core.A(
						core.Attrs{Href: "/admin/{{.RoutePlural}}/new", Class: "inline-flex items-center px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition"},
						core.Text("+ Add {{.Name}}"),
					),
				),

				// Table
				core.Div(core.Class("bg-gray-800 rounded-lg overflow-hidden"),
					core.Table(core.Class("w-full"),
						core.Thead(core.Class("bg-gray-700"),
							core.Tr(core.Attrs{},
								{{.Name}}TableHeaders()...,
							),
						),
						core.Tbody(core.Attrs{},
							{{.Name}}TableRows(displayItems)...,
						),
					),
				),
			),
		)
	}
}

func {{.Name}}TableHeaders() []core.Node {
	return []core.Node{
		tableHeader{{.Name}}("ID"),
{{range .TableFields}}		tableHeader{{$.Name}}("{{.Label}}"),
{{end}}		tableHeader{{$.Name}}("Actions"),
	}
}

func tableHeader{{.Name}}(text string) core.Node {
	return core.Th(core.Class("px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"),
		core.Text(text),
	)
}

func {{.Name}}TableRows(items []dto.{{.Name}}List) []core.Node {
	if len(items) == 0 {
		return []core.Node{
			core.Tr(core.Attrs{},
				core.Td(core.Class("px-6 py-4 text-gray-400 text-center"),
					core.Text("No {{.NamePluralLower}} found"),
				),
			),
		}
	}

	var rows []core.Node
	for _, item := range items {
		rows = append(rows, core.Tr(core.Class("border-t border-gray-700 hover:bg-gray-750"),
			tableCell{{.Name}}(fmt.Sprintf("%d", item.ID)),
{{range .TableFields}}			{{$.Name}}Cell{{.Name}}(item),
{{end}}			{{.Name}}ActionsCell(item.ID),
		))
	}
	return rows
}

func tableCell{{.Name}}(text string) core.Node {
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm text-gray-300"),
		core.Text(text),
	)
}

func {{.Name}}ActionsCell(id uint) core.Node {
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm"),
		core.A(
			core.Attrs{Href: fmt.Sprintf("/admin/{{.RoutePlural}}/%d", id), Class: "text-blue-400 hover:text-blue-300 mr-3"},
			core.Text("View"),
		),
	)
}

{{range .TableFields}}
func {{$.Name}}Cell{{.Name}}(item dto.{{$.Name}}List) core.Node {
{{- if .IsRelation}}
	text := "-"
	if item.{{.Name}} != nil {
		text = item.{{.Name}}.Name
	}
	return tableCell{{$.Name}}(text)
{{- else if .IsBool}}
	{{- if .Badge}}
	variant := "{{.Badge.FalseVariant}}"
	label := "{{.Badge.FalseLabel}}"
	if item.{{.Name}} {
		variant = "{{.Badge.TrueVariant}}"
		label = "{{.Badge.TrueLabel}}"
	}
	colorClass := "bg-gray-600"
	if variant == "success" {
		colorClass = "bg-green-600"
	} else if variant == "secondary" {
		colorClass = "bg-gray-600"
	}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap"),
		core.Span(core.Class("px-2 py-1 text-xs font-medium rounded "+colorClass+" text-white"),
			core.Text(label),
		),
	)
	{{- else}}
	text := "No"
	if item.{{.Name}} {
		text = "Yes"
	}
	return tableCell{{$.Name}}(text)
	{{- end}}
{{- else if .IsTime}}
	return tableCell{{$.Name}}(item.{{.Name}}.Format("Jan 2, 2006"))
{{- else}}
	return tableCell{{$.Name}}({{if eq .Type "int" "uint" "float64"}}fmt.Sprintf("%v", item.{{.Name}}){{else}}item.{{.Name}}{{end}})
{{- end}}
}
{{end}}
{{if .HasTime}}
func format{{.Name}}Time(t time.Time) string {
	return t.Format("Jan 2, 2006")
}
{{end}}`,

	AdminNew: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
{{- if .HasRelations}}
	"encoding/json"
{{- end}}
	"strconv"

	"github.com/dougbarrett/gux/core"
	"{{.ModulePath}}/.gux/api"
	"{{.ModulePath}}/dto"
)

// {{.Name}}New is the form for creating a new {{.NameLower}}.
func {{.Name}}New(r *core.Router) func() core.Node {
{{- range .Relations}}
	var {{.VarName}} []dto.{{.Model}}List
{{- end}}

	r.OnLoad(func() {
{{- range .Relations}}
		api.{{.ModelPlural}}.List(func(result []dto.{{.Model}}List, err error) {
			if err == nil {
				{{.VarName}} = result
			}
		})
{{- end}}
	})

	return func() core.Node {
		// Form state
{{range .AllFields}}		{{.StateVar}} := r.State{{.StateType}}("{{.StateName}}", {{.StateDefault}})
{{end}}		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")

{{- range .Relations}}
		// {{.Label}} state
		{{.VarName}}JSON, _ := json.Marshal({{.VarName}})
		{{.VarName}}State := r.StateString("{{.VarName}}", string({{.VarName}}JSON))
		var {{.VarName}}Options []dto.{{.Model}}List
		json.Unmarshal([]byte({{.VarName}}State.Get()), &{{.VarName}}Options)
{{- end}}

		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-green-900 border border-green-700 rounded-lg text-green-300"),
				core.Text(successState.Get()),
			)
		} else if errorState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-red-900 border border-red-700 rounded-lg text-red-300"),
				core.Text(errorState.Get()),
			)
		}

		save := func() {
			// Validate required fields
{{range .RequiredFields}}			if {{.StateVar}}.Get() == {{.EmptyValue}} {
				errorState.Set("{{.Label}} is required")
				return
			}
{{end}}
			data := map[string]any{
{{range .AllFields}}				"{{.JSONName}}": {{.DataValue}},
{{end}}			}

			api.{{.NamePlural}}.Create(data, func(result *dto.{{.Name}}Detail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("{{.Name}} created successfully!")
					r.Navigate("/admin/{{.RoutePlural}}")
				}
			})
		}

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: "/admin/{{.RoutePlural}}", Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to {{.NamePlural}}"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text("Create New {{.Name}}"),
				),

				messageNode,

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),
{{range $sectionName, $fields := .SectionedFields}}
					// {{$sectionName}}
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("{{$sectionName}}"),
						),
{{range $fields}}{{.FormField}}{{end}}					),
{{end}}
					// Submit
					core.Button(
						core.Attrs{
							Type:    "button",
							Class:   "w-full px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition",
							OnClick: save,
						},
						core.Text("Create {{.Name}}"),
					),
				),
			),
		)
	}
}

func {{.NameLower}}FormField(label, inputType, name, value string, onChange func(string), onEnter ...func()) core.Node {
	attrs := core.Attrs{
		Type:     inputType,
		Name:     name,
		Value:    value,
		Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
		OnChange: onChange,
	}
	if len(onEnter) > 0 {
		attrs.OnEnter = onEnter[0]
	}
	return core.Div(core.Class("mb-4"),
		core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
			core.Text(label),
		),
		core.Input(attrs),
	)
}
`,

	AdminDetail: `// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"

	"github.com/dougbarrett/gux/core"
	"{{.ModulePath}}/.gux/api"
	"{{.ModulePath}}/dto"
)

// {{.Name}}Detail shows a single {{.NameLower}}.
func {{.Name}}Detail(r *core.Router) func() core.Node {
	var item *dto.{{.Name}}Detail

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.{{.NamePlural}}.Get(uint(id), func(result *dto.{{.Name}}Detail, err error) {
			if err == nil {
				item = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.{{.Name}}Detail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.{{.Name}}Detail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)

		if displayItem.ID == 0 {
			return core.Div(core.Class("min-h-screen bg-gray-900"),
				Nav(),
				core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
					core.Text("{{.Name}} not found"),
				),
			)
		}

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: "/admin/{{.RoutePlural}}", Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to {{.NamePlural}}"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text(fmt.Sprintf("{{.Name}} #%d", displayItem.ID)),
				),

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),
{{range $sectionName, $fields := .SectionedFields}}
					// {{$sectionName}}
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("{{$sectionName}}"),
						),
{{range $fields}}{{.DetailField}}{{end}}					),
{{end}}
					// Timestamps
					core.Div(core.Class("mt-6 pt-4 border-t border-gray-700"),
						{{.NameLower}}DetailRow("Created", displayItem.CreatedAt.Format("Jan 2, 2006 3:04 PM")),
						{{.NameLower}}DetailRow("Updated", displayItem.UpdatedAt.Format("Jan 2, 2006 3:04 PM")),
					),
				),
			),
		)
	}
}

func {{.NameLower}}DetailRow(label, value string) core.Node {
	return core.Div(core.Class("flex py-2"),
		core.Div(core.Class("w-1/3 text-gray-400"),
			core.Text(label),
		),
		core.Div(core.Class("w-2/3 text-white"),
			core.Text(value),
		),
	)
}
`,
}

// TemplateField represents a field for template rendering
type TemplateField struct {
	Name         string
	Type         string
	GoType       string
	DTOType      string
	JSONName     string
	Label        string
	GormTag      string
	StateVar     string
	StateType    string
	StateName    string
	StateDefault string
	DataValue    string
	EmptyValue   string
	FormField    string
	DetailField  string
	Preload      string
	IsRelation   bool
	IsBool       bool
	IsTime       bool
	IsSlice      bool
	Badge        *BadgeConfig
}

// TemplateSection represents a section for template rendering
type TemplateSection struct {
	Name   string
	Fields []TemplateField
}

// TemplateRelation represents a relation for template rendering
type TemplateRelation struct {
	VarName     string
	Model       string
	ModelPlural string
	Label       string
}

// ModelTemplateData holds all data for model template rendering
type ModelTemplateData struct {
	Name            string
	NameLower       string
	NamePlural      string
	NamePluralLower string
	RoutePlural     string
	ModulePath      string
	Sections        []TemplateSection
	TableFields     []TemplateField
	AllFields       []TemplateField
	RequiredFields  []TemplateField
	Relations       []TemplateRelation
	SectionedFields map[string][]TemplateField
	HasTime         bool
	HasJSON         bool
	HasRelations    bool
	DisplayField    string
}

// GenerateModelFilesImpl generates all files for a model definition
func GenerateModelFilesImpl(model *ModelDefinition, optionSets map[string]OptionSet, modulePath string) error {
	// Prepare template data
	data := prepareModelTemplateData(model, modulePath)

	// Create directories if needed
	dirs := []string{"models", "dto", "admin"}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("create directory %s: %w", dir, err)
		}
	}

	// Generate model file
	modelPath := filepath.Join("models", ToSnakeCase(model.Name)+"_gen.go")
	if err := executeTemplate(ModelGenTemplates.Model, modelPath, data); err != nil {
		return fmt.Errorf("generate model: %w", err)
	}
	fmt.Printf("  %s\n", modelPath)

	// Generate DTO file
	dtoPath := filepath.Join("dto", ToSnakeCase(model.Name)+"_gen.go")
	if err := generateDTOFile(dtoPath, data); err != nil {
		return fmt.Errorf("generate dto: %w", err)
	}
	fmt.Printf("  %s\n", dtoPath)

	// Generate admin list page
	listPath := filepath.Join("admin", ToSnakeCase(ToPlural(model.Name))+"_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminList, listPath, data); err != nil {
		return fmt.Errorf("generate admin list: %w", err)
	}
	fmt.Printf("  %s\n", listPath)

	// Generate admin new page
	newPath := filepath.Join("admin", ToSnakeCase(model.Name)+"_new_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminNew, newPath, data); err != nil {
		return fmt.Errorf("generate admin new: %w", err)
	}
	fmt.Printf("  %s\n", newPath)

	// Generate admin detail page
	detailPath := filepath.Join("admin", ToSnakeCase(model.Name)+"_detail_gen.go")
	if err := executeTemplate(ModelGenTemplates.AdminDetail, detailPath, data); err != nil {
		return fmt.Errorf("generate admin detail: %w", err)
	}
	fmt.Printf("  %s\n", detailPath)

	return nil
}

func prepareModelTemplateData(model *ModelDefinition, modulePath string) *ModelTemplateData {
	data := &ModelTemplateData{
		Name:            model.Name,
		NameLower:       strings.ToLower(model.Name),
		NamePlural:      ToPlural(model.Name),
		NamePluralLower: strings.ToLower(ToPlural(model.Name)),
		RoutePlural:     ToSnakeCase(ToPlural(model.Name)),
		ModulePath:      modulePath,
		SectionedFields: make(map[string][]TemplateField),
		DisplayField:    "Name", // Default display field
	}

	// Process sections and fields
	for sectionName, fields := range model.Sections {
		var sectionFields []TemplateField

		for _, field := range fields {
			tf := convertToTemplateField(&field, model.Name)
			sectionFields = append(sectionFields, tf)
			data.AllFields = append(data.AllFields, tf)

			if field.Table {
				data.TableFields = append(data.TableFields, tf)
			}

			if field.Required {
				data.RequiredFields = append(data.RequiredFields, tf)
			}

			if field.Relation != "" {
				data.HasRelations = true
				data.Relations = append(data.Relations, TemplateRelation{
					VarName:     strings.ToLower(field.Relation) + "s",
					Model:       field.Relation,
					ModelPlural: ToPlural(field.Relation),
					Label:       getLabel(field),
				})
			}

			if tf.IsTime {
				data.HasTime = true
			}
			if tf.IsSlice && tf.Type == "[]string" {
				data.HasJSON = true
			}
		}

		data.Sections = append(data.Sections, TemplateSection{
			Name:   sectionName,
			Fields: sectionFields,
		})
		data.SectionedFields[sectionName] = sectionFields
	}

	return data
}

func convertToTemplateField(field *ModelField, modelName string) TemplateField {
	tf := TemplateField{
		Name:       field.Name,
		Type:       field.Type,
		GoType:     field.Type,
		DTOType:    field.Type,
		JSONName:   ToSnakeCase(field.Name),
		Label:      getLabel(*field),
		IsRelation: field.Relation != "",
		IsBool:     field.Type == "bool",
		IsTime:     field.Type == "time.Time" || field.Type == "*time.Time",
		IsSlice:    IsSliceType(field.Type),
		Badge:      field.Badge,
	}

	// Generate GORM tag
	tf.GormTag = generateGormTag(field)

	// Generate state helpers
	tf.StateVar = strings.ToLower(field.Name[:1]) + field.Name[1:] + "State"
	tf.StateName = ToSnakeCase(field.Name)

	switch field.Type {
	case "string":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = tf.StateVar + ".Get()"
	case "int", "uint":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseUint(%s.Get())", tf.StateVar)
	case "*uint":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseUintPtr(%s.Get())", tf.StateVar)
		tf.DTOType = fmt.Sprintf("*%sBrief", field.Relation) // No dto. prefix - same package
		tf.Preload = strings.TrimSuffix(field.Name, "ID")
	case "bool":
		tf.StateType = "Bool"
		tf.StateDefault = "false"
		tf.EmptyValue = "false"
		tf.DataValue = tf.StateVar + ".Get()"
	case "time.Time":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseTime(%s.Get())", tf.StateVar)
	case "*time.Time":
		tf.StateType = "String"
		tf.StateDefault = `""`
		tf.EmptyValue = `""`
		tf.DataValue = fmt.Sprintf("parseTimePtr(%s.Get())", tf.StateVar)
	case "[]string":
		tf.StateType = "String"
		tf.StateDefault = `"[]"`
		tf.EmptyValue = `"[]"`
		tf.DataValue = fmt.Sprintf("parseStringSlice(%s.Get())", tf.StateVar)
		tf.GoType = "StringList"
	default:
		if IsSliceType(field.Type) && field.Relation != "" {
			// M2M relation
			tf.StateType = "String"
			tf.StateDefault = `"[]"`
			tf.DTOType = fmt.Sprintf("[]%sBrief", field.Relation) // No dto. prefix - same package
			tf.Preload = field.Name
		}
	}

	// Generate form field code
	tf.FormField = generateFormFieldCode(field, tf)

	// Generate detail field code
	tf.DetailField = generateDetailFieldCode(field, tf)

	return tf
}

func getLabel(field ModelField) string {
	if field.Label != "" {
		return field.Label
	}
	// Convert PascalCase to Title Case with spaces
	var result strings.Builder
	for i, r := range field.Name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune(' ')
		}
		result.WriteRune(r)
	}
	return result.String()
}

func generateGormTag(field *ModelField) string {
	var tags []string

	if field.Required {
		tags = append(tags, "not null")
	}

	if field.Type == "[]string" {
		tags = append(tags, "type:json")
	}

	if field.Many2Many != "" {
		tags = append(tags, fmt.Sprintf("many2many:%s", field.Many2Many))
	}

	if field.Relation != "" && !IsSliceType(field.Type) {
		// FK field - no special tag needed, GORM handles it
	}

	jsonTag := fmt.Sprintf(`json:"%s"`, ToSnakeCase(field.Name))

	if len(tags) > 0 {
		return fmt.Sprintf("`%s gorm:\"%s\"`", jsonTag, strings.Join(tags, ";"))
	}
	return fmt.Sprintf("`%s`", jsonTag)
}

func generateFormFieldCode(field *ModelField, tf TemplateField) string {
	var buf strings.Builder
	indent := "\t\t\t\t\t\t"

	switch {
	case field.Input == "textarea":
		buf.WriteString(fmt.Sprintf(`%score.Div(core.Class("mb-4"),
%s	core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
%s		core.Text("%s"),
%s	),
%s	core.Textarea(core.Attrs{
%s		Name:     "%s",
%s		Value:    %s.Get(),
%s		Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
%s		OnChange: func(v string) { %s.Set(v) },
%s	}),
%s),
`, indent, indent, indent, tf.Label, indent, indent, indent, tf.StateName, indent, tf.StateVar, indent, indent, tf.StateVar, indent, indent))

	case field.Input == "select" || (field.Type == "*uint" && field.Relation != ""):
		// Select dropdown
		buf.WriteString(fmt.Sprintf(`%score.Div(core.Class("mb-4"),
%s	core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
%s		core.Text("%s"),
%s	),
%s	core.Select(
%s		core.Attrs{
%s			Name:  "%s",
%s			Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
%s			OnChange: func(v string) { %s.Set(v) },
%s		},
`, indent, indent, indent, tf.Label, indent, indent, indent, indent, tf.StateName, indent, indent, tf.StateVar, indent))

		if field.Relation != "" {
			// Dynamic options from relation
			varName := strings.ToLower(field.Relation) + "sOptions"
			buf.WriteString(fmt.Sprintf(`%s		core.Option(core.Attrs{Value: ""}, core.Text("Select %s")),
%s		%sSelectOptions(%s, %s.Get())...,
`, indent, tf.Label, indent, field.Relation, varName, tf.StateVar))
		} else {
			// Static options
			for _, opt := range field.Options {
				buf.WriteString(fmt.Sprintf(`%s		core.Option(core.Attrs{Value: "%s"}, core.Text("%s")),
`, indent, opt.Value, opt.Label))
			}
		}

		buf.WriteString(fmt.Sprintf(`%s	),
%s),
`, indent, indent))

	case field.Type == "bool":
		buf.WriteString(fmt.Sprintf(`%score.Div(core.Class("mb-4 flex items-center"),
%s	core.Input(core.Attrs{
%s		Type:    "checkbox",
%s		Name:    "%s",
%s		Checked: %s.Get(),
%s		Class:   "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-600 rounded bg-gray-700",
%s		OnChange: func(v string) { %s.Set(v == "true") },
%s	}),
%s	core.Label(core.Class("ml-2 block text-gray-300 text-sm"),
%s		core.Text("%s"),
%s	),
%s),
`, indent, indent, indent, indent, tf.StateName, indent, tf.StateVar, indent, indent, tf.StateVar, indent, indent, indent, tf.Label, indent, indent))

	default:
		// Standard input field
		inputType := "text"
		if field.Input != "" {
			inputType = field.Input
		} else if field.Type == "int" || field.Type == "uint" || field.Type == "float64" {
			inputType = "number"
		} else if strings.Contains(strings.ToLower(field.Name), "email") {
			inputType = "email"
		} else if strings.Contains(strings.ToLower(field.Name), "password") {
			inputType = "password"
		}

		buf.WriteString(fmt.Sprintf(`%s%sFormField("%s", "%s", "%s", %s.Get(), func(v string) { %s.Set(v) }, save),
`, indent, strings.ToLower(tf.Name[:1])+tf.Name[1:], tf.Label, inputType, tf.StateName, tf.StateVar, tf.StateVar))
	}

	return buf.String()
}

func generateDetailFieldCode(field *ModelField, tf TemplateField) string {
	indent := "\t\t\t\t\t\t"

	switch {
	case field.Relation != "" && !IsSliceType(field.Type):
		// FK relation - show related name
		preloadName := strings.TrimSuffix(field.Name, "ID")
		return fmt.Sprintf(`%s%sDetailRowPtr("%s", displayItem.%s),
`, indent, strings.ToLower(field.Name[:1])+field.Name[1:], tf.Label, preloadName)

	case field.Type == "bool":
		return fmt.Sprintf(`%s%sDetailRow("%s", func() string {
%s	if displayItem.%s {
%s		return "Yes"
%s	}
%s	return "No"
%s}()),
`, indent, strings.ToLower(field.Name[:1])+field.Name[1:], tf.Label, indent, field.Name, indent, indent, indent, indent)

	case field.Type == "time.Time" || field.Type == "*time.Time":
		return fmt.Sprintf(`%s%sDetailRow("%s", displayItem.%s.Format("Jan 2, 2006")),
`, indent, strings.ToLower(field.Name[:1])+field.Name[1:], tf.Label, field.Name)

	default:
		if field.Type == "int" || field.Type == "uint" || field.Type == "float64" {
			return fmt.Sprintf(`%s%sDetailRow("%s", fmt.Sprintf("%%v", displayItem.%s)),
`, indent, strings.ToLower(field.Name[:1])+field.Name[1:], tf.Label, field.Name)
		}
		return fmt.Sprintf(`%s%sDetailRow("%s", displayItem.%s),
`, indent, strings.ToLower(field.Name[:1])+field.Name[1:], tf.Label, field.Name)
	}
}

func generateDTOFile(path string, data *ModelTemplateData) error {
	// Check which Brief types already exist in the dto package
	existingTypes := findExistingDTOTypes(filepath.Dir(path))

	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Code generated by gux model; DO NOT EDIT.\npackage dto\n\n")

	// Always import time since Detail DTO includes CreatedAt/UpdatedAt
	buf.WriteString("import \"time\"\n\n")

	// Write List DTO
	buf.WriteString(fmt.Sprintf("// %sList is the DTO for %s list responses.\n", data.Name, data.NameLower))
	buf.WriteString(fmt.Sprintf("type %sList struct {\n", data.Name))
	buf.WriteString(fmt.Sprintf("\tID uint `json:\"id\" gux:\"%s.ID\"`\n", data.Name))
	for _, field := range data.TableFields {
		tag := fmt.Sprintf("`json:\"%s\" gux:\"%s.%s\"", field.JSONName, data.Name, field.Name)
		if field.Preload != "" {
			tag += fmt.Sprintf(" preload:\"%s\"", field.Preload)
		}
		tag += "`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", field.Name, field.DTOType, tag))
	}
	buf.WriteString("}\n\n")

	// Write Detail DTO
	buf.WriteString(fmt.Sprintf("// %sDetail is the DTO for single %s responses.\n", data.Name, data.NameLower))
	buf.WriteString(fmt.Sprintf("type %sDetail struct {\n", data.Name))
	buf.WriteString(fmt.Sprintf("\tID uint `json:\"id\" gux:\"%s.ID\"`\n", data.Name))
	for _, field := range data.AllFields {
		tag := fmt.Sprintf("`json:\"%s\" gux:\"%s.%s\"", field.JSONName, data.Name, field.Name)
		if field.Preload != "" {
			tag += fmt.Sprintf(" preload:\"%s\"", field.Preload)
		}
		tag += "`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", field.Name, field.DTOType, tag))
	}
	buf.WriteString(fmt.Sprintf("\tCreatedAt time.Time `json:\"created_at\" gux:\"%s.CreatedAt\"`\n", data.Name))
	buf.WriteString(fmt.Sprintf("\tUpdatedAt time.Time `json:\"updated_at\" gux:\"%s.UpdatedAt\"`\n", data.Name))
	buf.WriteString("}\n")

	// Write Brief DTOs for relations (only if they don't already exist)
	for _, rel := range data.Relations {
		briefTypeName := rel.Model + "Brief"
		if existingTypes[briefTypeName] {
			continue // Skip - already exists in another file
		}
		buf.WriteString(fmt.Sprintf("\n// %sBrief is a simplified %s DTO for embedding.\n", rel.Model, strings.ToLower(rel.Model)))
		buf.WriteString(fmt.Sprintf("type %sBrief struct {\n", rel.Model))
		buf.WriteString(fmt.Sprintf("\tID   uint   `json:\"id\" gux:\"%s.ID\"`\n", rel.Model))
		buf.WriteString(fmt.Sprintf("\tName string `json:\"name\" gux:\"%s.Name\"`\n", rel.Model))
		buf.WriteString("}\n")
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}

// findExistingDTOTypes scans the dto directory for existing type declarations
func findExistingDTOTypes(dtoDir string) map[string]bool {
	types := make(map[string]bool)

	files, err := os.ReadDir(dtoDir)
	if err != nil {
		return types // Directory may not exist yet
	}

	for _, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".go") {
			continue
		}
		// Skip generated files (we'll regenerate them)
		if strings.HasSuffix(file.Name(), "_gen.go") {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dtoDir, file.Name()))
		if err != nil {
			continue
		}

		// Simple regex to find type declarations
		// Matches: type TypeName struct
		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "type ") && strings.Contains(line, " struct") {
				parts := strings.Fields(line)
				if len(parts) >= 2 {
					types[parts[1]] = true
				}
			}
		}
	}

	return types
}

func executeTemplate(tmplText, path string, data *ModelTemplateData) error {
	tmpl, err := template.New("").Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}
