// Code generated by gux model; DO NOT EDIT.
package models

import (
	"gorm.io/gorm"
)

// Client is a GORM model.
type Client struct {
	gorm.Model

	// Contact
	FirstName string `json:"first_name" gorm:"not null"`
	LastName string `json:"last_name" gorm:"not null"`
	Email string `json:"email"`
	Phone string `json:"phone"`

	// Lead Info
	SalespersonID *uint `json:"salesperson_id"`
	ClosedLead bool `json:"closed_lead"`

	// Business
	State string `json:"state"`
	Description string `json:"description"`

}
