// Code generated by gux; DO NOT EDIT.
package main

import (
	_ "embed"

	"github.com/dougbarrett/gux/core"
)

//go:embed guxgen/dist/app.wasm
var wasmBinary []byte

//go:embed guxgen/dist/wasm_exec.js
var wasmExecJS []byte

//go:embed guxgen/dist/styles.css
var stylesCSS []byte

//go:embed guxgen/dist/admin.wasm
var wasmAdmin []byte

func init() {
	core.SetDefaultAssets(wasmBinary, wasmExecJS, stylesCSS)
	core.SetDefaultBundle("admin", wasmAdmin)
	core.SetDefaultAssetHashes("10a4bca1", map[string]string{"app": "78dff0eb", "admin": "db87dcfe", })
}
