// Code generated by gux; DO NOT EDIT.
package main

import (
	_ "embed"

	"github.com/dougbarrett/gux/core"
)

//go:embed .gux/dist/app.wasm
var wasmBinary []byte

//go:embed .gux/dist/wasm_exec.js
var wasmExecJS []byte

//go:embed .gux/dist/styles.css
var stylesCSS []byte

	func init() {
		core.SetDefaultAssets(wasmBinary, wasmExecJS, stylesCSS)
	}
