//go:build !js || !wasm

// Code generated by gux; DO NOT EDIT.
// Server-side implementation - queries database directly.
package api

import (
	"encoding/json"

	"gorm.io/gorm"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/examples/audit/dto"
	"github.com/dougbarrett/gux/examples/audit/models"
)

var db *gorm.DB

// Init initializes the API with a database connection.
func Init(database interface{}) {
	if gormDB, ok := database.(*gorm.DB); ok {
		db = gormDB
	}
}

// Post is a stub for server-side builds.
func Post[T any](url string, data any, callback func(T, error)) {
	var zero T
	callback(zero, nil)
}

// --- Users API ---

// UsersAPI provides CRUD operations for User.
type UsersAPI struct{}

// Users is the API client for User operations.
var Users = &UsersAPI{}

// List returns all User records.
func (a *UsersAPI) List(callback func([]dto.UserList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var items []models.User
	if err := db.Find(&items).Error; err != nil {
		callback(nil, err)
		return
	}
	result := make([]dto.UserList, len(items))
	for i, item := range items {
		result[i] = dto.UserList{
			ID:        item.ID,
			Email:     item.Email,
			Name:      item.Name,
			Role:      item.Role,
			CreatedAt: item.CreatedAt,
		}
	}
	callback(result, nil)
}

// Get returns a single User by ID.
func (a *UsersAPI) Get(id uint, callback func(*dto.UserDetail, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var item models.User
	if err := db.First(&item, id).Error; err != nil {
		callback(nil, err)
		return
	}
	result := &dto.UserDetail{
		ID:        item.ID,
		Email:     item.Email,
		Name:      item.Name,
		Role:      item.Role,
		CreatedAt: item.CreatedAt,
		UpdatedAt: item.UpdatedAt,
	}
	callback(result, nil)
}

// Create creates a new User (server-side stub).
func (a *UsersAPI) Create(data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	callback(nil, nil)
}

// Update updates an existing User (server-side stub).
func (a *UsersAPI) Update(id uint, data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	callback(nil, nil)
}

// Delete deletes a User by ID (server-side stub).
func (a *UsersAPI) Delete(id uint, callback func(error)) {
	callback(nil)
}

// --- Documents API ---

// DocumentsAPI provides CRUD operations for Document.
type DocumentsAPI struct{}

// Documents is the API client for Document operations.
var Documents = &DocumentsAPI{}

// List returns all Document records.
func (a *DocumentsAPI) List(callback func([]dto.DocumentList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var items []models.Document
	if err := db.Find(&items).Error; err != nil {
		callback(nil, err)
		return
	}
	result := make([]dto.DocumentList, len(items))
	for i, item := range items {
		result[i] = dto.DocumentList{
			ID:        item.ID,
			Title:     item.Title,
			Status:    item.Status,
			AuthorID:  item.AuthorID,
			CreatedAt: item.CreatedAt,
		}
	}
	callback(result, nil)
}

// Get returns a single Document by ID.
func (a *DocumentsAPI) Get(id uint, callback func(*dto.DocumentDetail, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var item models.Document
	if err := db.First(&item, id).Error; err != nil {
		callback(nil, err)
		return
	}
	result := &dto.DocumentDetail{
		ID:        item.ID,
		Title:     item.Title,
		Content:   item.Content,
		Status:    item.Status,
		AuthorID:  item.AuthorID,
		CreatedAt: item.CreatedAt,
		UpdatedAt: item.UpdatedAt,
	}
	callback(result, nil)
}

// Create creates a new Document (server-side stub).
func (a *DocumentsAPI) Create(data map[string]interface{}, callback func(*dto.DocumentDetail, error)) {
	callback(nil, nil)
}

// Update updates an existing Document (server-side stub).
func (a *DocumentsAPI) Update(id uint, data map[string]interface{}, callback func(*dto.DocumentDetail, error)) {
	callback(nil, nil)
}

// Delete deletes a Document by ID (server-side stub).
func (a *DocumentsAPI) Delete(id uint, callback func(error)) {
	callback(nil)
}

// --- AuditEntries API ---

// AuditEntriesAPI provides read operations for AuditEntry.
type AuditEntriesAPI struct{}

// AuditEntries is the API client for AuditEntry operations.
var AuditEntries = &AuditEntriesAPI{}

// List returns all AuditEntry records.
func (a *AuditEntriesAPI) List(callback func([]dto.AuditEntryList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var items []core.AuditEntry
	if err := db.Order("created_at desc").Find(&items).Error; err != nil {
		callback(nil, err)
		return
	}
	result := make([]dto.AuditEntryList, len(items))
	for i, item := range items {
		result[i] = dto.AuditEntryList{
			ID:         item.ID,
			CreatedAt:  item.CreatedAt,
			Action:     string(item.Action),
			EntityType: item.EntityType,
			EntityID:   item.EntityID,
			UserID:     item.UserID,
			UserEmail:  item.UserEmail,
			IPAddress:  item.IPAddress,
			Changes:    item.Changes,
		}
	}
	callback(result, nil)
}

// LoginResponse is the response from the login API.
type LoginResponse struct {
	Success  bool   `json:"success"`
	Error    string `json:"error,omitempty"`
	Redirect string `json:"redirect,omitempty"`
}

// Login is a no-op on server side (login happens via HTTP POST in browser).
func Login(data map[string]interface{}, callback func(LoginResponse, error)) {
	callback(LoginResponse{}, nil)
}

// Ensure imports are used.
var _ json.Marshaler
