//go:build js && wasm

// Code generated by gux; DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"syscall/js"

	"github.com/dougbarrett/gux/examples/audit/dto"
)

// Init is a no-op in WASM (database not available).
func Init(db interface{}) {}

// getCSRFToken reads the CSRF token from the meta tag.
func getCSRFToken() string {
	doc := js.Global().Get("document")
	meta := doc.Call("querySelector", "meta[name=\"csrf-token\"]")
	if meta.IsNull() || meta.IsUndefined() {
		return ""
	}
	return meta.Get("content").String()
}

// fetch makes an HTTP request and returns the response body.
func fetch(method, url string, body []byte) ([]byte, error) {
	done := make(chan struct{})
	var result []byte
	var fetchErr error

	jsOpts := js.Global().Get("Object").New()
	jsOpts.Set("method", method)
	headers := js.Global().Get("Object").New()
	headers.Set("Content-Type", "application/json")

	if method == "POST" || method == "PUT" || method == "PATCH" || method == "DELETE" {
		if token := getCSRFToken(); token != "" {
			headers.Set("X-CSRF-Token", token)
		}
	}

	jsOpts.Set("headers", headers)
	if body != nil {
		jsOpts.Set("body", string(body))
	}

	promise := js.Global().Call("fetch", url, jsOpts)

	var thenFunc, catchFunc js.Func
	thenFunc = js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		resp := args[0]
		if !resp.Get("ok").Bool() {
			fetchErr = errors.New("request failed: " + resp.Get("statusText").String())
			close(done)
			return nil
		}
		resp.Call("text").Call("then", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
			result = []byte(args[0].String())
			close(done)
			return nil
		}))
		return nil
	})
	catchFunc = js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		fetchErr = errors.New("fetch error: " + args[0].Get("message").String())
		close(done)
		return nil
	})

	promise.Call("then", thenFunc).Call("catch", catchFunc)

	<-done
	return result, fetchErr
}

// Post makes a POST request to the given URL with JSON body.
func Post[T any](url string, data any, callback func(T, error)) {
	go func() {
		body, err := json.Marshal(data)
		if err != nil {
			var zero T
			callback(zero, err)
			return
		}
		resp, err := fetch("POST", url, body)
		if err != nil {
			var zero T
			callback(zero, err)
			return
		}
		var result T
		if err := json.Unmarshal(resp, &result); err != nil {
			var zero T
			callback(zero, err)
			return
		}
		callback(result, nil)
	}()
}

// --- Users API ---

// UsersAPI provides CRUD operations for User.
type UsersAPI struct {
	baseURL string
}

// Users is the API client for User operations.
var Users = &UsersAPI{baseURL: "/__gux_api/crud/users"}

// List returns all User records.
func (a *UsersAPI) List(callback func([]dto.UserList, error)) {
	go func() {
		resp, err := fetch("GET", a.baseURL, nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var items []dto.UserList
		if err := json.Unmarshal(resp, &items); err != nil {
			callback(nil, err)
			return
		}
		callback(items, nil)
	}()
}

// Get returns a single User by ID.
func (a *UsersAPI) Get(id uint, callback func(*dto.UserDetail, error)) {
	go func() {
		resp, err := fetch("GET", fmt.Sprintf("%s/%d", a.baseURL, id), nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.UserDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Create creates a new User.
func (a *UsersAPI) Create(data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("POST", a.baseURL, body)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.UserDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Update updates an existing User.
func (a *UsersAPI) Update(id uint, data map[string]interface{}, callback func(*dto.UserDetail, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("PUT", fmt.Sprintf("%s/%d", a.baseURL, id), body)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.UserDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Delete deletes a User by ID.
func (a *UsersAPI) Delete(id uint, callback func(error)) {
	go func() {
		_, err := fetch("DELETE", fmt.Sprintf("%s/%d", a.baseURL, id), nil)
		callback(err)
	}()
}

// --- Documents API ---

// DocumentsAPI provides CRUD operations for Document.
type DocumentsAPI struct {
	baseURL string
}

// Documents is the API client for Document operations.
var Documents = &DocumentsAPI{baseURL: "/__gux_api/crud/documents"}

// List returns all Document records.
func (a *DocumentsAPI) List(callback func([]dto.DocumentList, error)) {
	go func() {
		resp, err := fetch("GET", a.baseURL, nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var items []dto.DocumentList
		if err := json.Unmarshal(resp, &items); err != nil {
			callback(nil, err)
			return
		}
		callback(items, nil)
	}()
}

// Get returns a single Document by ID.
func (a *DocumentsAPI) Get(id uint, callback func(*dto.DocumentDetail, error)) {
	go func() {
		resp, err := fetch("GET", fmt.Sprintf("%s/%d", a.baseURL, id), nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.DocumentDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Create creates a new Document.
func (a *DocumentsAPI) Create(data map[string]interface{}, callback func(*dto.DocumentDetail, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("POST", a.baseURL, body)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.DocumentDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Update updates an existing Document.
func (a *DocumentsAPI) Update(id uint, data map[string]interface{}, callback func(*dto.DocumentDetail, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("PUT", fmt.Sprintf("%s/%d", a.baseURL, id), body)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.DocumentDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Delete deletes a Document by ID.
func (a *DocumentsAPI) Delete(id uint, callback func(error)) {
	go func() {
		_, err := fetch("DELETE", fmt.Sprintf("%s/%d", a.baseURL, id), nil)
		callback(err)
	}()
}

// --- AuditEntries API ---

// AuditEntriesAPI provides read operations for AuditEntry.
type AuditEntriesAPI struct {
	baseURL string
}

// AuditEntries is the API client for AuditEntry operations.
var AuditEntries = &AuditEntriesAPI{baseURL: "/__gux_api/crud/auditentries"}

// List returns all AuditEntry records.
func (a *AuditEntriesAPI) List(callback func([]dto.AuditEntryList, error)) {
	go func() {
		resp, err := fetch("GET", a.baseURL, nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var items []dto.AuditEntryList
		if err := json.Unmarshal(resp, &items); err != nil {
			callback(nil, err)
			return
		}
		callback(items, nil)
	}()
}

// LoginResponse is the response from the login API.
type LoginResponse struct {
	Success  bool   `json:"success"`
	Error    string `json:"error,omitempty"`
	Redirect string `json:"redirect,omitempty"`
}

// Login posts login credentials to /api/login.
func Login(data map[string]interface{}, callback func(LoginResponse, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("POST", "/api/login", body)
		if err != nil {
			callback(LoginResponse{}, err)
			return
		}
		var result LoginResponse
		if err := json.Unmarshal(resp, &result); err != nil {
			callback(LoginResponse{}, err)
			return
		}
		callback(result, nil)
	}()
}
