//go:build js && wasm

// Code generated by gux; DO NOT EDIT.
// API endpoint client for typed API endpoints.
package api

import (
	"encoding/json"
	"errors"

	guxfetch "github.com/dougbarrett/gux/fetch"
)

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Success  bool   `json:"success"`
	Error    string `json:"error,omitempty"`
	Redirect string `json:"redirect,omitempty"`
}

// apiEndpointFetch makes an HTTP request and returns the response body
func apiEndpointFetch(method, url string, body []byte) ([]byte, error) {
	opts := &guxfetch.Options{
		Method: method,
		Headers: map[string]string{
			"Content-Type": "application/json",
		},
	}
	if body != nil {
		opts.Body = string(body)
	}

	resp, err := guxfetch.Fetch(url, opts)
	if err != nil {
		return nil, err
	}
	if !resp.OK {
		return nil, errors.New(resp.StatusText)
	}
	return []byte(resp.Body), nil
}

// Login calls POST /api/login
func Login(req LoginRequest, callback func(LoginResponse, error)) {
	go func() {
		body, err := json.Marshal(req)
		if err != nil {
			var zero LoginResponse
			callback(zero, err)
			return
		}
		resp, err := apiEndpointFetch("POST", "/api/login", body)
		if err != nil {
			var zero LoginResponse
			callback(zero, err)
			return
		}
		var result LoginResponse
		if err := json.Unmarshal(resp, &result); err != nil {
			var zero LoginResponse
			callback(zero, err)
			return
		}
		callback(result, nil)
	}()
}

