//go:build !js || !wasm

// Code generated by gux; DO NOT EDIT.
// Server-side implementation for typed API endpoints.
// Makes HTTP requests to the API during SSR.
package api

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
)

// endpointBaseURL is the base URL for API calls during SSR.
// Set via InitEndpoints() or defaults to http://localhost:PORT.
var endpointBaseURL = ""

// endpointSessionID stores the current session ID for SSR requests.
// This allows API calls during SSR to inherit the user's authentication.
var endpointSessionID = ""

// endpointSessionCookieName is the name of the session cookie.
var endpointSessionCookieName = "__gux_session"

// InitEndpoints sets the base URL for server-side API calls.
// Call this in your main() before starting the server.
// If not called, defaults to http://localhost:$PORT or http://localhost:8080.
func InitEndpoints(baseURL string) {
	endpointBaseURL = baseURL
}

// SetEndpointSession sets the session ID and cookie name for SSR API calls.
// This should be called before rendering pages that make API calls.
// The session is automatically propagated to API requests made during SSR.
func SetEndpointSession(sessionID, cookieName string) {
	endpointSessionID = sessionID
	if cookieName != "" {
		endpointSessionCookieName = cookieName
	}
}

// ClearEndpointSession clears the session after page rendering is complete.
func ClearEndpointSession() {
	endpointSessionID = ""
}

// getEndpointBaseURL returns the base URL for API calls.
func getEndpointBaseURL() string {
	if endpointBaseURL != "" {
		return endpointBaseURL
	}
	// Try to get from PORT environment variable
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	return "http://localhost:" + port
}

// endpointFetch makes an HTTP request to the API endpoint.
// If a session ID is set, it will be passed as a cookie for authentication.
func endpointFetch(method, path string, body []byte) ([]byte, error) {
	url := getEndpointBaseURL() + path

	var reqBody io.Reader
	if body != nil {
		reqBody = bytes.NewReader(body)
	}

	req, err := http.NewRequest(method, url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")

	// Pass session cookie if available (for SSR auth propagation)
	if endpointSessionID != "" {
		req.AddCookie(&http.Cookie{
			Name:  endpointSessionCookieName,
			Value: endpointSessionID,
		})
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("API error: %s", string(respBody))
	}

	return respBody, nil
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Success  bool   `json:"success"`
	Error    string `json:"error,omitempty"`
	Redirect string `json:"redirect,omitempty"`
}

// Login calls POST /api/login
func Login(req LoginRequest, callback func(LoginResponse, error)) {
	body, err := json.Marshal(req)
	if err != nil {
		var zero LoginResponse
		callback(zero, err)
		return
	}
	resp, err := endpointFetch("POST", "/api/login", body)
	if err != nil {
		var zero LoginResponse
		callback(zero, err)
		return
	}
	var result LoginResponse
	if err := json.Unmarshal(resp, &result); err != nil {
		var zero LoginResponse
		callback(zero, err)
		return
	}
	callback(result, nil)
}
