// Code generated by gux pages; DO NOT EDIT.
package pages

// Router provides page context and state management.
type Router struct {
	state    map[string]any
	rerender func()
}

// NewRouter creates a new router instance.
func NewRouter(rerender func()) *Router {
	return &Router{
		state:    make(map[string]any),
		rerender: rerender,
	}
}

// State represents a reactive state value.
type State[T any] struct {
	key    string
	router *Router
}

// Get returns the current state value.
func (s *State[T]) Get() T {
	if val, ok := s.router.state[s.key]; ok {
		return val.(T)
	}
	var zero T
	return zero
}

// Set updates the state and triggers re-render.
func (s *State[T]) Set(val T) {
	s.router.state[s.key] = val
	if s.router.rerender != nil {
		s.router.rerender()
	}
}

// StateInt creates an integer state.
func (r *Router) StateInt(key string, initial int) *State[int] {
	if _, ok := r.state[key]; !ok {
		r.state[key] = initial
	}
	return &State[int]{key: key, router: r}
}

// StateBool creates a boolean state.
func (r *Router) StateBool(key string, initial bool) *State[bool] {
	if _, ok := r.state[key]; !ok {
		r.state[key] = initial
	}
	return &State[bool]{key: key, router: r}
}

// StateString creates a string state.
func (r *Router) StateString(key string, initial string) *State[string] {
	if _, ok := r.state[key]; !ok {
		r.state[key] = initial
	}
	return &State[string]{key: key, router: r}
}
