// Code generated by gux pages; DO NOT EDIT.
//go:build !js

package pages

import (
	"fmt"
	"net/http"

	"github.com/dougbarrett/gux/core"
)

// RegisterRoutes registers all page routes with the given mux.
func RegisterRoutes(mux *http.ServeMux, shell func(content string) string) {
	router := NewRouter(nil) // No rerender for SSR

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		component := router.Home()
		html := component().Render(core.HTML()).HTML()
		w.Header().Set("Content-Type", "text/html")
		fmt.Fprint(w, shell(html))
	})

}
