// Code generated by gux pages; DO NOT EDIT.
//go:build js && wasm

package pages

import (
	"syscall/js"

	"github.com/dougbarrett/gux/core"
)

// Mount initializes the WASM application.
func Mount(containerID string) {
	document := js.Global().Get("document")
	container := document.Call("getElementById", containerID)

	var router *Router
	var render func()

	render = func() {
		container.Set("innerHTML", "")

		// Route based on current path
		path := js.Global().Get("location").Get("pathname").String()
		var component func() core.Node

		switch path {
		case "/":
			component = router.Home()
		default:
			component = router.Home()
		}

		node := component()
		result := node.Render(core.DOM())
		if domVal := result.DOMValue(); domVal != nil {
			container.Call("appendChild", domVal.(js.Value))
		}
	}

	router = NewRouter(render)
	render()
}
