// Code generated by gux; DO NOT EDIT.
package main

import (
	_ "embed"

	"github.com/dougbarrett/gux/core"
)

//go:embed guxgen/dist/app.wasm
var wasmBinary []byte

//go:embed guxgen/dist/wasm_exec.js
var wasmExecJS []byte

//go:embed guxgen/dist/styles.css
var stylesCSS []byte

func init() {
	core.SetDefaultAssets(wasmBinary, wasmExecJS, stylesCSS)
	core.SetDefaultAssetHashes("5b6acb26", map[string]string{"app": "922b4d59", })
}
