// Code generated by apigen. DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// ClientOption configures a client
type ClientOption func(*clientConfig)

type clientConfig struct {
	baseURL    string
	basePath   string
	httpClient *http.Client
}

// WithBaseURL sets the base URL for API calls (e.g., "https://api.example.com")
func WithBaseURL(url string) ClientOption {
	return func(c *clientConfig) {
		c.baseURL = url
	}
}

// WithBasePath overrides the default API path prefix (e.g., "/api/v1/posts")
func WithBasePath(path string) ClientOption {
	return func(c *clientConfig) {
		c.basePath = path
	}
}

// WithHTTPClient sets a custom HTTP client
func WithHTTPClient(client *http.Client) ClientOption {
	return func(c *clientConfig) {
		c.httpClient = client
	}
}

func doRequest[T any](ctx context.Context, cfg *clientConfig, method, path string, body any) (T, error) {
	var result T

	url := cfg.baseURL + cfg.basePath + path

	var reqBody *bytes.Reader
	if body != nil {
		data, err := json.Marshal(body)
		if err != nil {
			return result, fmt.Errorf("marshal request: %w", err)
		}
		reqBody = bytes.NewReader(data)
	}

	var req *http.Request
	var err error
	if reqBody != nil {
		req, err = http.NewRequestWithContext(ctx, method, url, reqBody)
	} else {
		req, err = http.NewRequestWithContext(ctx, method, url, nil)
	}
	if err != nil {
		return result, fmt.Errorf("create request: %w", err)
	}

	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := cfg.httpClient.Do(req)
	if err != nil {
		return result, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return result, fmt.Errorf("unexpected status %d", resp.StatusCode)
	}

	// For DELETE or no-content responses
	if resp.ContentLength == 0 {
		return result, nil
	}

	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return result, fmt.Errorf("decode response: %w", err)
	}

	return result, nil
}

func doRequestNoResponse(ctx context.Context, cfg *clientConfig, method, path string) error {
	url := cfg.baseURL + cfg.basePath + path

	req, err := http.NewRequestWithContext(ctx, method, url, nil)
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}

	resp, err := cfg.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("unexpected status %d", resp.StatusCode)
	}

	return nil
}


// PostsClient is a client for PostsAPI
type PostsClient struct {
	cfg *clientConfig
}

// NewPostsClient creates a new PostsClient
func NewPostsClient(opts ...ClientOption) *PostsClient {
	cfg := &clientConfig{
		baseURL:    "",
		basePath:   "/api/posts",
		httpClient: http.DefaultClient,
	}
	for _, opt := range opts {
		opt(cfg)
	}
	return &PostsClient{cfg: cfg}
}


// GetAll fetches data via GET /api/posts/
func (c *PostsClient) GetAll(ctx context.Context) ([]Post, error) {
	return doRequest[[]Post](ctx, c.cfg, "GET", "/", nil)
}

// GetByID fetches data via GET /api/posts/{id}
func (c *PostsClient) GetByID(ctx context.Context, id int) (*Post, error) {
	result, err := doRequest[Post](ctx, c.cfg, "GET", fmt.Sprintf("/%d", id), nil)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create creates data via POST /api/posts/
func (c *PostsClient) Create(ctx context.Context, req CreatePostRequest) (*Post, error) {
	result, err := doRequest[Post](ctx, c.cfg, "POST", "/", req)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update updates data via PUT /api/posts/{id}
func (c *PostsClient) Update(ctx context.Context, id int, req CreatePostRequest) (*Post, error) {
	result, err := doRequest[Post](ctx, c.cfg, "PUT", fmt.Sprintf("/%d", id), req)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete deletes data via DELETE /api/posts/{id}
func (c *PostsClient) Delete(ctx context.Context, id int) error {
	return doRequestNoResponse(ctx, c.cfg, "DELETE", fmt.Sprintf("/%d", id))
}


