//go:build !js || !wasm

// Code generated by gux; DO NOT EDIT.
// Server-side implementation - queries database directly.
package api

import (
	"gorm.io/gorm"

	"github.com/dougbarrett/gux/examples/saas/models"

	"github.com/dougbarrett/gux/examples/saas/dto"
)

var db *gorm.DB

// Init initializes the API with a database connection.
// Called automatically by the gux framework.
func Init(database *gorm.DB) {
	db = database
}

// ProjectsAPI provides CRUD operations for Project.
type ProjectsAPI struct{}

// Projects is the API client for Project operations.
var Projects = &ProjectsAPI{}

// List returns all Project records.
func (a *ProjectsAPI) List(callback func([]dto.ProjectList, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var items []models.Project
	if err := db.Find(&items).Error; err != nil {
		callback(nil, err)
		return
	}
	// Convert to DTOs using field mappings from gux tags
	result := make([]dto.ProjectList, len(items))
	for i, item := range items {
		result[i] = dto.ProjectList{
			ID: item.ID,
			Name: item.Name,
			Status: item.Status,
			CreatedAt: item.CreatedAt,
		}
	}
	callback(result, nil)
}

// Get returns a single Project by ID.
func (a *ProjectsAPI) Get(id uint, callback func(*dto.ProjectDetail, error)) {
	if db == nil {
		callback(nil, nil)
		return
	}
	var item models.Project
	if err := db.First(&item, id).Error; err != nil {
		callback(nil, err)
		return
	}
	result := &dto.ProjectDetail{
			ID: item.ID,
			Name: item.Name,
			Description: item.Description,
			Status: item.Status,
			CreatedAt: item.CreatedAt,
			UpdatedAt: item.UpdatedAt,
	}
	callback(result, nil)
}

// Create creates a new Project (server-side stub - actual creation handled by CRUD endpoint).
func (a *ProjectsAPI) Create(data map[string]interface{}, callback func(*dto.ProjectDetail, error)) {
	// Server-side: this is typically not called directly
	// The CRUD endpoint handles creation with hooks
	callback(nil, nil)
}

// Update updates an existing Project (server-side stub).
func (a *ProjectsAPI) Update(id uint, data map[string]interface{}, callback func(*dto.ProjectDetail, error)) {
	// Server-side: this is typically not called directly
	callback(nil, nil)
}

// Delete deletes a Project by ID (server-side stub).
func (a *ProjectsAPI) Delete(id uint, callback func(error)) {
	// Server-side: this is typically not called directly
	callback(nil)
}

