//go:build js && wasm

// Code generated by gux; DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"syscall/js"

	"github.com/dougbarrett/gux/examples/saas/dto"
)

// Init is a no-op in WASM (database not available).
func Init(db interface{}) {}

// fetch makes an HTTP request and returns the response body.
func fetch(method, url string, body []byte) ([]byte, error) {
	done := make(chan struct{})
	var result []byte
	var fetchErr error

	// Create JS object for headers
	jsOpts := js.Global().Get("Object").New()
	jsOpts.Set("method", method)
	headers := js.Global().Get("Object").New()
	headers.Set("Content-Type", "application/json")
	jsOpts.Set("headers", headers)
	if body != nil {
		jsOpts.Set("body", string(body))
	}

	// Call fetch
	promise := js.Global().Call("fetch", url, jsOpts)

	// Handle response
	var thenFunc, catchFunc js.Func
	thenFunc = js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		resp := args[0]
		if !resp.Get("ok").Bool() {
			fetchErr = errors.New("request failed: " + resp.Get("statusText").String())
			close(done)
			return nil
		}
		// Get response text
		resp.Call("text").Call("then", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
			result = []byte(args[0].String())
			close(done)
			return nil
		}))
		return nil
	})
	catchFunc = js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		fetchErr = errors.New("fetch error: " + args[0].Get("message").String())
		close(done)
		return nil
	})

	promise.Call("then", thenFunc).Call("catch", catchFunc)

	<-done
	return result, fetchErr
}

// ProjectsAPI provides read operations for Project with DTO responses.
type ProjectsAPI struct {
	baseURL string
}

// Projects is the API client for Project operations.
var Projects = &ProjectsAPI{baseURL: "/__gux_api/crud/projects"}

// List returns all Project records using ProjectList DTO.
func (a *ProjectsAPI) List(callback func([]dto.ProjectList, error)) {
	go func() {
		resp, err := fetch("GET", a.baseURL, nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var items []dto.ProjectList
		if err := json.Unmarshal(resp, &items); err != nil {
			callback(nil, err)
			return
		}
		callback(items, nil)
	}()
}

// Get returns a single Project by ID using ProjectDetail DTO.
func (a *ProjectsAPI) Get(id uint, callback func(*dto.ProjectDetail, error)) {
	go func() {
		resp, err := fetch("GET", fmt.Sprintf("%s/%d", a.baseURL, id), nil)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.ProjectDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Create creates a new Project with the given data.
func (a *ProjectsAPI) Create(data map[string]interface{}, callback func(*dto.ProjectDetail, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("POST", a.baseURL, body)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.ProjectDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Update updates an existing Project.
func (a *ProjectsAPI) Update(id uint, data map[string]interface{}, callback func(*dto.ProjectDetail, error)) {
	go func() {
		body, _ := json.Marshal(data)
		resp, err := fetch("PUT", fmt.Sprintf("%s/%d", a.baseURL, id), body)
		if err != nil {
			callback(nil, err)
			return
		}
		var item dto.ProjectDetail
		if err := json.Unmarshal(resp, &item); err != nil {
			callback(nil, err)
			return
		}
		callback(&item, nil)
	}()
}

// Delete deletes a Project by ID.
func (a *ProjectsAPI) Delete(id uint, callback func(error)) {
	go func() {
		_, err := fetch("DELETE", fmt.Sprintf("%s/%d", a.baseURL, id), nil)
		callback(err)
	}()
}

