// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/ui"
	"github.com/dougbarrett/gux/examples/minimal/guxgen/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// ClientNew is the form for creating a new client.
func ClientNew(r *core.Router) func() core.Node {
	var users []dto.UserList

	r.OnLoad(func() {
		api.Users.List(func(result []dto.UserList, err error) {
			if err == nil {
				users = result
			}
		})
	})

	return func() core.Node {
		// Form state
		firstNameState := r.StateString("first_name", "")
		lastNameState := r.StateString("last_name", "")
		emailState := r.StateString("email", "")
		phoneState := r.StateString("phone", "")
		salespersonIDState := r.StateString("salesperson_id", "")
		closedLeadState := r.StateBool("closed_lead", false)
		stateState := r.StateString("state", "")
		descriptionState := r.StateString("description", "")
		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")
		// Salesperson state
		usersJSON, _ := json.Marshal(users)
		usersState := r.StateString("users", string(usersJSON))
		var usersOptions []dto.UserList
		json.Unmarshal([]byte(usersState.Get()), &usersOptions)
		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertSuccess,
				Message: successState.Get(),
			})
		} else if errorState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}

		save := func() {
			// Validate required fields
			if firstNameState.Get() == "" {
				errorState.Set("First Name is required")
				return
			}
			if lastNameState.Get() == "" {
				errorState.Set("Last Name is required")
				return
			}

			data := map[string]any{
				"first_name": firstNameState.Get(),
				"last_name": lastNameState.Get(),
				"email": emailState.Get(),
				"phone": phoneState.Get(),
				"salesperson_id": parseUintPtr(salespersonIDState.Get()),
				"closed_lead": closedLeadState.Get(),
				"state": stateState.Get(),
				"description": descriptionState.Get(),
			}

			api.Clients.Create(data, func(result *dto.ClientDetail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("Client created successfully!")
					r.Navigate("/admin/clients")
				}
			})
		}
		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "Clients", Href: "/admin/clients"},
					{Label: "Create New"},
				},
				Title: "Create New Client",
			}),
			messageNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{

							// Business
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Business"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("State"),
							),
							core.Select(
								core.Attrs{
									Name:  "state",
									Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
									OnChange: func(v string) { stateState.Set(v) },
								},
								core.Option(core.Attrs{Value: "CA"}, core.Text("California")),
								core.Option(core.Attrs{Value: "NY"}, core.Text("New York")),
								core.Option(core.Attrs{Value: "TX"}, core.Text("Texas")),
							),
						),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("Description"),
							),
							core.Textarea(core.Attrs{
								Name:     "description",
								Value:    descriptionState.Get(),
								Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
								OnChange: func(v string) { descriptionState.Set(v) },
							}),
						),
								),
							),

							// Contact
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Contact"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						clientFormField("First Name", "text", "first_name", firstNameState.Get(), func(v string) { firstNameState.Set(v) }, save),
						clientFormField("Last Name", "text", "last_name", lastNameState.Get(), func(v string) { lastNameState.Set(v) }, save),
						clientFormField("Email", "email", "email", emailState.Get(), func(v string) { emailState.Set(v) }, save),
						clientFormField("Phone", "tel", "phone", phoneState.Get(), func(v string) { phoneState.Set(v) }, save),
								),
							),

							// Lead Info
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Lead Info"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("Salesperson"),
							),
							core.Select(
								core.Attrs{
									Name:  "salesperson_id",
									Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
									OnChange: func(v string) { salespersonIDState.Set(v) },
								},
								func() []core.Node {
									opts := []core.Node{core.Option(core.Attrs{Value: ""}, core.Text("Select Salesperson"))}
									for _, item := range usersOptions {
										idStr := strconv.FormatUint(uint64(item.ID), 10)
										attrs := core.Attrs{Value: idStr}
										if idStr == salespersonIDState.Get() {
											attrs.Extra = map[string]string{"selected": "selected"}
										}
										opts = append(opts, core.Option(attrs, core.Text(fmt.Sprintf("#%d", item.ID))))
									}
									return opts
								}()...,
							),
						),
						core.Div(core.Class("mb-4 flex items-center"),
							core.Input(func() core.Attrs {
								attrs := core.Attrs{
									Type:    "checkbox",
									Name:    "closed_lead",
									Class:   "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-600 rounded bg-gray-700",
									OnChange: func(v string) { closedLeadState.Set(v == "true") },
								}
								if closedLeadState.Get() {
									attrs.Extra = map[string]string{"checked": "checked"}
								}
								return attrs
							}()),
							core.Label(core.Class("ml-2 block text-gray-300 text-sm"),
								core.Text("Closed Lead"),
							),
						),
								),
							),

							// Submit
							ui.Button(ui.ButtonProps{
								Variant:  ui.ButtonPrimary,
								Class:    "w-full mt-4",
								OnClick:  save,
								Children: []core.Node{core.Text("Create Client")},
							}),
						},
					}),
				},
			}),
		)
	}
}

func clientFormField(label, inputType, name, value string, onChange func(string), onEnter ...func()) core.Node {
	attrs := core.Attrs{
		Type:     inputType,
		Name:     name,
		Value:    value,
		Class:    "w-full px-4 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white focus:outline-none focus:border-blue-500",
		OnChange: onChange,
	}
	if len(onEnter) > 0 {
		attrs.OnEnter = onEnter[0]
	}
	return core.Div(core.Class("mb-4"),
		core.Label(core.Class("block text-gray-700 dark:text-gray-300 text-sm font-medium mb-2"),
			core.Text(label),
		),
		core.Input(attrs),
	)
}

func parseUint(s string) uint {
	if s == "" {
		return 0
	}
	v, _ := strconv.ParseUint(s, 10, 64)
	return uint(v)
}

func parseUintPtr(s string) *uint {
	if s == "" {
		return nil
	}
	v, _ := strconv.ParseUint(s, 10, 64)
	u := uint(v)
	return &u
}
