// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/ui"
	"github.com/dougbarrett/gux/examples/minimal/guxgen/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// Clients is the admin clients list page.
func Clients(r *core.Router) func() core.Node {
	var items []dto.ClientList

	r.OnLoad(func() {
		api.Clients.List(func(result []dto.ClientList, err error) {
			if err == nil {
				items = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		itemsJSON, _ := json.Marshal(items)
		itemsState := r.StateString("items", string(itemsJSON))

		// Parse from state
		var displayItems []dto.ClientList
		json.Unmarshal([]byte(itemsState.Get()), &displayItems)
		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "Clients"},
				},
				Title:    "Clients",
				Subtitle: fmt.Sprintf("%d total", len(displayItems)),
				Actions: []core.Node{
					core.A(
						core.Attrs{
							Href:  "/admin/clients/new",
							Class: "inline-flex items-center gap-2 text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 font-medium",
						},
						core.Span(core.Class("text-lg"), core.Text("+")),
						core.Text("Add Client"),
					),
				},
			}),
			ui.Card(ui.CardProps{
				Children: []core.Node{
					core.Table(core.Class("w-full"),
						core.Thead(core.Class("bg-gray-100 dark:bg-gray-700"),
							core.Tr(core.Attrs{},
								ClientTableHeaders()...,
							),
						),
						core.Tbody(core.Attrs{},
							ClientTableRows(displayItems, r)...,
						),
					),
				},
			}),
		)
	}
}

func ClientTableHeaders() []core.Node {
	return []core.Node{
		tableHeaderClient("ID"),
		tableHeaderClient("Salesperson"),
		tableHeaderClient("Closed Lead"),
		tableHeaderClient("First Name"),
		tableHeaderClient("Last Name"),
		tableHeaderClient("Email"),
		tableHeaderClient("Actions"),
	}
}

func tableHeaderClient(text string) core.Node {
	return core.Th(core.Class("px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"),
		core.Text(text),
	)
}

func ClientTableRows(items []dto.ClientList, r *core.Router) []core.Node {
	if len(items) == 0 {
		return []core.Node{
			core.Tr(core.Attrs{},
				core.Td(core.Class("px-6 py-4 text-gray-500 dark:text-gray-400 text-center"),
					core.Text("No clients found"),
				),
			),
		}
	}

	var rows []core.Node
	for _, item := range items {
		rows = append(rows, core.Tr(core.Class("border-t border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-750"),
			tableCellClient(fmt.Sprintf("%d", item.ID)),
			ClientCellSalespersonID(item),
			ClientCellClosedLead(item),
			ClientCellFirstName(item),
			ClientCellLastName(item),
			ClientCellEmail(item),
			ClientActionsCell(item.ID, r),
		))
	}
	return rows
}

func tableCellClient(text string) core.Node {
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm text-gray-700 dark:text-gray-300"),
		core.Text(text),
	)
}

func ClientActionsCell(id uint, r *core.Router) core.Node {
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm"),
		ui.Button(ui.ButtonProps{
			Variant:  ui.ButtonGhost,
			Size:     ui.ButtonSM,
			Children: []core.Node{core.Text("View")},
			OnClick:  func() { r.Navigate(fmt.Sprintf("/admin/clients/%d", id)) },
		}),
	)
}


func ClientCellSalespersonID(item dto.ClientList) core.Node {
	text := "-"
	if item.Salesperson != nil {
		text = item.Salesperson.Name
	}
	return tableCellClient(text)
}

func ClientCellClosedLead(item dto.ClientList) core.Node {
	variant := "secondary"
	label := "Open"
	if item.ClosedLead {
		variant = "success"
		label = "Closed"
	}
	colorClass := "bg-gray-600"
	if variant == "success" {
		colorClass = "bg-green-600"
	} else if variant == "secondary" {
		colorClass = "bg-gray-600"
	}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap"),
		core.Span(core.Class("px-2 py-1 text-xs font-medium rounded "+colorClass+" text-white"),
			core.Text(label),
		),
	)
}

func ClientCellFirstName(item dto.ClientList) core.Node {
	// Display field is clickable - links to detail page
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm"),
		core.A(
			core.Attrs{
				Href:  fmt.Sprintf("/admin/clients/%d", item.ID),
				Class: "text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 font-medium",
			},
			core.Text(item.FirstName),
		),
	)
}

func ClientCellLastName(item dto.ClientList) core.Node {
	return tableCellClient(item.LastName)
}

func ClientCellEmail(item dto.ClientList) core.Node {
	return tableCellClient(item.Email)
}


