// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/examples/minimal/.gux/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// ClientDetail shows a single client.
func ClientDetail(r *core.Router) func() core.Node {
	var item *dto.ClientDetail

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.Clients.Get(uint(id), func(result *dto.ClientDetail, err error) {
			if err == nil {
				item = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.ClientDetail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.ClientDetail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)

		if displayItem.ID == 0 {
			return core.Div(core.Class("min-h-screen bg-gray-900"),
				Nav(),
				core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
					core.Text("Client not found"),
				),
			)
		}

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: "/admin/clients", Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to Clients"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text(fmt.Sprintf("Client #%d", displayItem.ID)),
				),

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),

					// Business
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("Business"),
						),
						stateDetailRow("State", displayItem.State),
						descriptionDetailRow("Description", displayItem.Description),
					),

					// Contact
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("Contact"),
						),
						firstNameDetailRow("First Name", displayItem.FirstName),
						lastNameDetailRow("Last Name", displayItem.LastName),
						emailDetailRow("Email", displayItem.Email),
						phoneDetailRow("Phone", displayItem.Phone),
					),

					// Lead Info
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("Lead Info"),
						),
						salespersonIDDetailRowPtr("Salesperson", displayItem.Salesperson),
						closedLeadDetailRow("Closed Lead", func() string {
							if displayItem.ClosedLead {
								return "Yes"
							}
							return "No"
						}()),
					),

					// Timestamps
					core.Div(core.Class("mt-6 pt-4 border-t border-gray-700"),
						clientDetailRow("Created", displayItem.CreatedAt.Format("Jan 2, 2006 3:04 PM")),
						clientDetailRow("Updated", displayItem.UpdatedAt.Format("Jan 2, 2006 3:04 PM")),
					),
				),
			),
		)
	}
}

func clientDetailRow(label, value string) core.Node {
	return core.Div(core.Class("flex py-2"),
		core.Div(core.Class("w-1/3 text-gray-400"),
			core.Text(label),
		),
		core.Div(core.Class("w-2/3 text-white"),
			core.Text(value),
		),
	)
}
