// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"strconv"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/examples/minimal/.gux/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// ClientNew is the form for creating a new client.
func ClientNew(r *core.Router) func() core.Node {
	var users []dto.UserList

	r.OnLoad(func() {
		api.Users.List(func(result []dto.UserList, err error) {
			if err == nil {
				users = result
			}
		})
	})

	return func() core.Node {
		// Form state
		firstNameState := r.StateString("first_name", "")
		lastNameState := r.StateString("last_name", "")
		emailState := r.StateString("email", "")
		phoneState := r.StateString("phone", "")
		salespersonIDState := r.StateString("salesperson_id", "")
		closedLeadState := r.StateBool("closed_lead", false)
		stateState := r.StateString("state", "")
		descriptionState := r.StateString("description", "")
		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")
		// Salesperson state
		usersJSON, _ := json.Marshal(users)
		usersState := r.StateString("users", string(usersJSON))
		var usersOptions []dto.UserList
		json.Unmarshal([]byte(usersState.Get()), &usersOptions)

		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-green-900 border border-green-700 rounded-lg text-green-300"),
				core.Text(successState.Get()),
			)
		} else if errorState.Get() != "" {
			messageNode = core.Div(core.Class("mb-4 p-4 bg-red-900 border border-red-700 rounded-lg text-red-300"),
				core.Text(errorState.Get()),
			)
		}

		save := func() {
			// Validate required fields
			if firstNameState.Get() == "" {
				errorState.Set("First Name is required")
				return
			}
			if lastNameState.Get() == "" {
				errorState.Set("Last Name is required")
				return
			}

			data := map[string]any{
				"first_name": firstNameState.Get(),
				"last_name": lastNameState.Get(),
				"email": emailState.Get(),
				"phone": phoneState.Get(),
				"salesperson_id": parseUintPtr(salespersonIDState.Get()),
				"closed_lead": closedLeadState.Get(),
				"state": stateState.Get(),
				"description": descriptionState.Get(),
			}

			api.Clients.Create(data, func(result *dto.ClientDetail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("Client created successfully!")
					r.Navigate("/admin/clients")
				}
			})
		}

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-2xl mx-auto px-4 py-8"),
				core.A(
					core.Attrs{Href: "/admin/clients", Class: "text-blue-400 hover:text-blue-300 mb-4 inline-block"},
					core.Text("\u2190 Back to Clients"),
				),

				core.H1(core.Class("text-2xl font-bold text-white mb-6"),
					core.Text("Create New Client"),
				),

				messageNode,

				core.Div(core.Class("bg-gray-800 rounded-lg p-6"),

					// Business
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("Business"),
						),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("State"),
							),
							core.Select(
								core.Attrs{
									Name:  "state",
									Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
									OnChange: func(v string) { stateState.Set(v) },
								},
								core.Option(core.Attrs{Value: "CA"}, core.Text("California")),
								core.Option(core.Attrs{Value: "NY"}, core.Text("New York")),
								core.Option(core.Attrs{Value: "TX"}, core.Text("Texas")),
							),
						),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("Description"),
							),
							core.Textarea(core.Attrs{
								Name:     "description",
								Value:    descriptionState.Get(),
								Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
								OnChange: func(v string) { descriptionState.Set(v) },
							}),
						),
					),

					// Contact
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("Contact"),
						),
						firstNameFormField("First Name", "text", "first_name", firstNameState.Get(), func(v string) { firstNameState.Set(v) }, save),
						lastNameFormField("Last Name", "text", "last_name", lastNameState.Get(), func(v string) { lastNameState.Set(v) }, save),
						emailFormField("Email", "email", "email", emailState.Get(), func(v string) { emailState.Set(v) }, save),
						phoneFormField("Phone", "tel", "phone", phoneState.Get(), func(v string) { phoneState.Set(v) }, save),
					),

					// Lead Info
					core.Div(core.Class("mb-6"),
						core.H3(core.Class("text-lg font-semibold text-white mb-4"),
							core.Text("Lead Info"),
						),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("Salesperson"),
							),
							core.Select(
								core.Attrs{
									Name:  "salesperson_id",
									Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
									OnChange: func(v string) { salespersonIDState.Set(v) },
								},
								core.Option(core.Attrs{Value: ""}, core.Text("Select Salesperson")),
								UserSelectOptions(usersOptions, salespersonIDState.Get())...,
							),
						),
						core.Div(core.Class("mb-4 flex items-center"),
							core.Input(core.Attrs{
								Type:    "checkbox",
								Name:    "closed_lead",
								Checked: closedLeadState.Get(),
								Class:   "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-600 rounded bg-gray-700",
								OnChange: func(v string) { closedLeadState.Set(v == "true") },
							}),
							core.Label(core.Class("ml-2 block text-gray-300 text-sm"),
								core.Text("Closed Lead"),
							),
						),
					),

					// Submit
					core.Button(
						core.Attrs{
							Type:    "button",
							Class:   "w-full px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition",
							OnClick: save,
						},
						core.Text("Create Client"),
					),
				),
			),
		)
	}
}

func clientFormField(label, inputType, name, value string, onChange func(string), onEnter ...func()) core.Node {
	attrs := core.Attrs{
		Type:     inputType,
		Name:     name,
		Value:    value,
		Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
		OnChange: onChange,
	}
	if len(onEnter) > 0 {
		attrs.OnEnter = onEnter[0]
	}
	return core.Div(core.Class("mb-4"),
		core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
			core.Text(label),
		),
		core.Input(attrs),
	)
}
