// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/ui"
	"github.com/dougbarrett/gux/examples/minimal/guxgen/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// ClientDetail shows a single client.
func ClientDetail(r *core.Router) func() core.Node {
	var item *dto.ClientDetail

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.Clients.Get(uint(id), func(result *dto.ClientDetail, err error) {
			if err == nil {
				item = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.ClientDetail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.ClientDetail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)
		// Delete confirmation state
		confirmDelete := r.StateBool("confirm_delete", false)
		errorState := r.StateString("error", "")

		if displayItem.ID == 0 {
			return core.Frag(
				ui.PageHeader(ui.PageHeaderProps{
					Breadcrumbs: []ui.BreadcrumbItem{
						{Label: "Admin", Href: "/admin"},
						{Label: "Clients", Href: "/admin/clients"},
						{Label: "Not Found"},
					},
					Title: "Client Not Found",
				}),
				ui.Alert(ui.AlertProps{
					Variant: ui.AlertError,
					Message: "The requested client could not be found.",
				}),
			)
		}

		// Build display name from display field
		displayName := displayItem.FirstName
		if displayName == "" {
			displayName = fmt.Sprintf("Client #%d", displayItem.ID)
		}

		// Delete handler
		handleDelete := func() {
			if confirmDelete.Get() {
				api.Clients.Delete(displayItem.ID, func(err error) {
					if err != nil {
						errorState.Set(err.Error())
						confirmDelete.Set(false)
					} else {
						r.Navigate("/admin/clients")
					}
				})
			} else {
				confirmDelete.Set(true)
			}
		}

		// Build action buttons
		var actions []core.Node
		if confirmDelete.Get() {
			actions = []core.Node{
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonGhost,
					Children: []core.Node{core.Text("Cancel")},
					OnClick:  func() { confirmDelete.Set(false) },
				}),
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonDestructive,
					Children: []core.Node{core.Text("Confirm Delete")},
					OnClick:  handleDelete,
				}),
			}
		} else {
			actions = []core.Node{
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonPrimary,
					Children: []core.Node{core.Text("Edit")},
					OnClick:  func() { r.Navigate(fmt.Sprintf("/admin/clients/%d/edit", displayItem.ID)) },
				}),
				ui.Button(ui.ButtonProps{
					Variant:  ui.ButtonDestructive,
					Children: []core.Node{core.Text("Delete")},
					OnClick:  handleDelete,
				}),
			}
		}

		var errorNode core.Node = core.Frag()
		if errorState.Get() != "" {
			errorNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}

		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "Clients", Href: "/admin/clients"},
					{Label: displayName},
				},
				Title:   displayName,
				Actions: actions,
			}),
			errorNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{

							// Business
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Business"),
								),
						clientDetailRow("State", displayItem.State),
						clientDetailRow("Description", displayItem.Description),
							),

							// Contact
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Contact"),
								),
						clientDetailRow("First Name", displayItem.FirstName),
						clientDetailRow("Last Name", displayItem.LastName),
						clientDetailRow("Email", displayItem.Email),
						clientDetailRow("Phone", displayItem.Phone),
							),

							// Lead Info
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Lead Info"),
								),
						clientDetailRow("Salesperson", func() string {
							if displayItem.Salesperson != nil {
								return displayItem.Salesperson.Name
							}
							return "-"
						}()),
						clientDetailRow("Closed Lead", func() string {
							if displayItem.ClosedLead {
								return "Yes"
							}
							return "No"
						}()),
							),

							// Timestamps
							core.Div(core.Class("mt-6 pt-4 border-t border-gray-200 dark:border-gray-700"),
								clientDetailRow("Created", displayItem.CreatedAt.Format("Jan 2, 2006 3:04 PM")),
								clientDetailRow("Updated", displayItem.UpdatedAt.Format("Jan 2, 2006 3:04 PM")),
							),
						},
					}),
				},
			}),
		)
	}
}

func clientDetailRow(label, value string) core.Node {
	return core.Div(core.Class("flex py-2"),
		core.Div(core.Class("w-1/3 text-gray-500 dark:text-gray-400"),
			core.Text(label),
		),
		core.Div(core.Class("w-2/3 text-gray-900 dark:text-white"),
			core.Text(value),
		),
	)
}
