// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/examples/minimal/.gux/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// Clients is the admin clients list page.
func Clients(r *core.Router) func() core.Node {
	var items []dto.ClientList

	r.OnLoad(func() {
		api.Clients.List(func(result []dto.ClientList, err error) {
			if err == nil {
				items = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		itemsJSON, _ := json.Marshal(items)
		itemsState := r.StateString("items", string(itemsJSON))

		// Parse from state
		var displayItems []dto.ClientList
		json.Unmarshal([]byte(itemsState.Get()), &displayItems)

		return core.Div(core.Class("min-h-screen bg-gray-900"),
			Nav(),
			core.Div(core.Class("max-w-6xl mx-auto px-4 py-8"),
				core.H1(core.Class("text-3xl font-bold text-white mb-8"),
					core.Text("Clients"),
				),

				// Add button
				core.Div(core.Class("mb-4"),
					core.A(
						core.Attrs{Href: "/admin/clients/new", Class: "inline-flex items-center px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition"},
						core.Text("+ Add Client"),
					),
				),

				// Table
				core.Div(core.Class("bg-gray-800 rounded-lg overflow-hidden"),
					core.Table(core.Class("w-full"),
						core.Thead(core.Class("bg-gray-700"),
							core.Tr(core.Attrs{},
								ClientTableHeaders()...,
							),
						),
						core.Tbody(core.Attrs{},
							ClientTableRows(displayItems)...,
						),
					),
				),
			),
		)
	}
}

func ClientTableHeaders() []core.Node {
	return []core.Node{
		tableHeaderClient("ID"),
		tableHeaderClient("First Name"),
		tableHeaderClient("Last Name"),
		tableHeaderClient("Email"),
		tableHeaderClient("Salesperson"),
		tableHeaderClient("Closed Lead"),
		tableHeaderClient("Actions"),
	}
}

func tableHeaderClient(text string) core.Node {
	return core.Th(core.Class("px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"),
		core.Text(text),
	)
}

func ClientTableRows(items []dto.ClientList) []core.Node {
	if len(items) == 0 {
		return []core.Node{
			core.Tr(core.Attrs{},
				core.Td(core.Class("px-6 py-4 text-gray-400 text-center"),
					core.Text("No clients found"),
				),
			),
		}
	}

	var rows []core.Node
	for _, item := range items {
		rows = append(rows, core.Tr(core.Class("border-t border-gray-700 hover:bg-gray-750"),
			tableCellClient(fmt.Sprintf("%d", item.ID)),
			ClientCellFirstName(item),
			ClientCellLastName(item),
			ClientCellEmail(item),
			ClientCellSalespersonID(item),
			ClientCellClosedLead(item),
			ClientActionsCell(item.ID),
		))
	}
	return rows
}

func tableCellClient(text string) core.Node {
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm text-gray-300"),
		core.Text(text),
	)
}

func ClientActionsCell(id uint) core.Node {
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap text-sm"),
		core.A(
			core.Attrs{Href: fmt.Sprintf("/admin/clients/%d", id), Class: "text-blue-400 hover:text-blue-300 mr-3"},
			core.Text("View"),
		),
	)
}


func ClientCellFirstName(item dto.ClientList) core.Node {
	return tableCellClient(item.FirstName)
}

func ClientCellLastName(item dto.ClientList) core.Node {
	return tableCellClient(item.LastName)
}

func ClientCellEmail(item dto.ClientList) core.Node {
	return tableCellClient(item.Email)
}

func ClientCellSalespersonID(item dto.ClientList) core.Node {
	text := "-"
	if item.SalespersonID != nil {
		text = item.SalespersonID.Name
	}
	return tableCellClient(text)
}

func ClientCellClosedLead(item dto.ClientList) core.Node {
	variant := "secondary"
	label := "Open"
	if item.ClosedLead {
		variant = "success"
		label = "Closed"
	}
	colorClass := "bg-gray-600"
	if variant == "success" {
		colorClass = "bg-green-600"
	} else if variant == "secondary" {
		colorClass = "bg-gray-600"
	}
	return core.Td(core.Class("px-6 py-4 whitespace-nowrap"),
		core.Span(core.Class("px-2 py-1 text-xs font-medium rounded "+colorClass+" text-white"),
			core.Text(label),
		),
	)
}

