// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/ui"
	"github.com/dougbarrett/gux/examples/minimal/guxgen/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// ClientEdit is the form for editing an existing client.
func ClientEdit(r *core.Router) func() core.Node {
	var item *dto.ClientDetail
	var users []dto.UserList

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.Clients.Get(uint(id), func(result *dto.ClientDetail, err error) {
			if err == nil {
				item = result
			}
		})
		api.Users.List(func(result []dto.UserList, err error) {
			if err == nil {
				users = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.ClientDetail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.ClientDetail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)
		// Salesperson state
		usersJSON, _ := json.Marshal(users)
		usersState := r.StateString("users", string(usersJSON))
		var usersOptions []dto.UserList
		json.Unmarshal([]byte(usersState.Get()), &usersOptions)
		if displayItem.ID == 0 {
			return core.Frag(
				ui.PageHeader(ui.PageHeaderProps{
					Breadcrumbs: []ui.BreadcrumbItem{
						{Label: "Admin", Href: "/admin"},
						{Label: "Clients", Href: "/admin/clients"},
						{Label: "Not Found"},
					},
					Title: "Client Not Found",
				}),
				ui.Alert(ui.AlertProps{
					Variant: ui.AlertError,
					Message: "The requested client could not be found.",
				}),
			)
		}

		// Build display name from display field
		displayName := displayItem.FirstName
		if displayName == "" {
			displayName = fmt.Sprintf("Client #%d", displayItem.ID)
		}

		// Form state - initialize with current values
		salespersonIDState := r.StateString("salesperson_id", func() string { if displayItem.Salesperson != nil { return fmt.Sprintf("%d", displayItem.Salesperson.ID) }; return "" }())
		closedLeadState := r.StateBool("closed_lead", displayItem.ClosedLead)
		stateState := r.StateString("state", displayItem.State)
		descriptionState := r.StateString("description", displayItem.Description)
		firstNameState := r.StateString("first_name", displayItem.FirstName)
		lastNameState := r.StateString("last_name", displayItem.LastName)
		emailState := r.StateString("email", displayItem.Email)
		phoneState := r.StateString("phone", displayItem.Phone)
		errorState := r.StateString("error", "")
		successState := r.StateString("success", "")

		var messageNode core.Node = core.Frag()
		if successState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertSuccess,
				Message: successState.Get(),
			})
		} else if errorState.Get() != "" {
			messageNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}

		save := func() {
			// Validate required fields
			if firstNameState.Get() == "" {
				errorState.Set("First Name is required")
				return
			}
			if lastNameState.Get() == "" {
				errorState.Set("Last Name is required")
				return
			}

			data := map[string]any{
				"salesperson_id": parseUintPtr(salespersonIDState.Get()),
				"closed_lead": closedLeadState.Get(),
				"state": stateState.Get(),
				"description": descriptionState.Get(),
				"first_name": firstNameState.Get(),
				"last_name": lastNameState.Get(),
				"email": emailState.Get(),
				"phone": phoneState.Get(),
			}

			api.Clients.Update(displayItem.ID, data, func(result *dto.ClientDetail, err error) {
				if err != nil {
					errorState.Set(err.Error())
				} else {
					successState.Set("Client updated successfully!")
					r.Navigate(fmt.Sprintf("/admin/clients/%d", displayItem.ID))
				}
			})
		}

		return core.Frag(
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "Clients", Href: "/admin/clients"},
					{Label: displayName, Href: fmt.Sprintf("/admin/clients/%d", displayItem.ID)},
					{Label: "Edit"},
				},
				Title: fmt.Sprintf("Edit %s", displayName),
			}),
			messageNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{

							// Business
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Business"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("State"),
							),
							core.Select(
								core.Attrs{
									Name:  "state",
									Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
									OnChange: func(v string) { stateState.Set(v) },
								},
								core.Option(core.Attrs{Value: "CA"}, core.Text("California")),
								core.Option(core.Attrs{Value: "NY"}, core.Text("New York")),
								core.Option(core.Attrs{Value: "TX"}, core.Text("Texas")),
							),
						),
						core.Div(core.Class("mb-4 md:col-span-2"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("Description"),
							),
							core.Textarea(core.Attrs{
								Name:     "description",
								Value:    descriptionState.Get(),
								Class:    "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
								OnChange: func(v string) { descriptionState.Set(v) },
							}),
						),
								),
							),

							// Contact
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Contact"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						clientFormField("First Name", "text", "first_name", firstNameState.Get(), func(v string) { firstNameState.Set(v) }, save),
						clientFormField("Last Name", "text", "last_name", lastNameState.Get(), func(v string) { lastNameState.Set(v) }, save),
						clientFormField("Email", "email", "email", emailState.Get(), func(v string) { emailState.Set(v) }, save),
						clientFormField("Phone", "tel", "phone", phoneState.Get(), func(v string) { phoneState.Set(v) }, save),
								),
							),

							// Lead Info
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Lead Info"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						core.Div(core.Class("mb-4"),
							core.Label(core.Class("block text-gray-300 text-sm font-medium mb-2"),
								core.Text("Salesperson"),
							),
							core.Select(
								core.Attrs{
									Name:  "salesperson_id",
									Class: "w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-blue-500",
									OnChange: func(v string) { salespersonIDState.Set(v) },
								},
								func() []core.Node {
									opts := []core.Node{core.Option(core.Attrs{Value: ""}, core.Text("Select Salesperson"))}
									for _, item := range usersOptions {
										idStr := strconv.FormatUint(uint64(item.ID), 10)
										attrs := core.Attrs{Value: idStr}
										if idStr == salespersonIDState.Get() {
											attrs.Extra = map[string]string{"selected": "selected"}
										}
										opts = append(opts, core.Option(attrs, core.Text(fmt.Sprintf("#%d", item.ID))))
									}
									return opts
								}()...,
							),
						),
						core.Div(core.Class("mb-4 flex items-center"),
							core.Input(func() core.Attrs {
								attrs := core.Attrs{
									Type:    "checkbox",
									Name:    "closed_lead",
									Class:   "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-600 rounded bg-gray-700",
									OnChange: func(v string) { closedLeadState.Set(v == "true") },
								}
								if closedLeadState.Get() {
									attrs.Extra = map[string]string{"checked": "checked"}
								}
								return attrs
							}()),
							core.Label(core.Class("ml-2 block text-gray-300 text-sm"),
								core.Text("Closed Lead"),
							),
						),
								),
							),

							// Submit
							ui.Button(ui.ButtonProps{
								Variant:  ui.ButtonPrimary,
								Class:    "w-full mt-4",
								OnClick:  save,
								Children: []core.Node{core.Text("Save Changes")},
							}),
						},
					}),
				},
			}),
		)
	}
}
