// Code generated by gux model; DO NOT EDIT.
package admin

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/dougbarrett/gux/core"
	"github.com/dougbarrett/gux/ui"
	"github.com/dougbarrett/gux/examples/minimal/guxgen/api"
	"github.com/dougbarrett/gux/examples/minimal/dto"
)

// ClientDetail shows a single client.
func ClientDetail(r *core.Router) func() core.Node {
	var item *dto.ClientDetail

	r.OnLoad(func() {
		idStr := r.Param("id")
		id, err := strconv.ParseUint(idStr, 10, 64)
		if err != nil {
			return
		}
		api.Clients.Get(uint(id), func(result *dto.ClientDetail, err error) {
			if err == nil {
				item = result
			}
		})
	})

	return func() core.Node {
		// Store in state for hydration
		var itemData dto.ClientDetail
		if item != nil {
			itemData = *item
		}
		itemJSON, _ := json.Marshal(itemData)
		itemState := r.StateString("item", string(itemJSON))

		var displayItem dto.ClientDetail
		json.Unmarshal([]byte(itemState.Get()), &displayItem)
		// Delete confirmation modal state
		showDeleteModal := r.StateBool("show_delete_modal", false)
		errorState := r.StateString("error", "")

		if displayItem.ID == 0 {
			return core.Frag(
				ui.PageHeader(ui.PageHeaderProps{
					Breadcrumbs: []ui.BreadcrumbItem{
						{Label: "Admin", Href: "/admin"},
						{Label: "Clients", Href: "/admin/clients"},
						{Label: "Not Found"},
					},
					Title: "Client Not Found",
				}),
				ui.Alert(ui.AlertProps{
					Variant: ui.AlertError,
					Message: "The requested client could not be found.",
				}),
			)
		}

		// Build display name from display field
		displayName := displayItem.FirstName
		if displayName == "" {
			displayName = fmt.Sprintf("Client #%d", displayItem.ID)
		}

		// Get initials for avatar
		initials := clientGetInitials(displayName)

		// Delete handler - called when confirming in modal
		confirmDelete := func() {
			api.Clients.Delete(displayItem.ID, func(err error) {
				if err != nil {
					errorState.Set(err.Error())
					showDeleteModal.Set(false)
				} else {
					r.Navigate("/admin/clients")
				}
			})
		}

		// Action buttons - always show Edit and Delete
		actions := []core.Node{
			ui.Button(ui.ButtonProps{
				Variant:  ui.ButtonPrimary,
				Children: []core.Node{core.Text("Edit")},
				OnClick:  func() { r.Navigate(fmt.Sprintf("/admin/clients/%d/edit", displayItem.ID)) },
			}),
			ui.Button(ui.ButtonProps{
				Variant:  ui.ButtonDestructive,
				Children: []core.Node{core.Text("Delete")},
				OnClick:  func() { showDeleteModal.Set(true) },
			}),
		}

		var errorNode core.Node = core.Frag()
		if errorState.Get() != "" {
			errorNode = ui.Alert(ui.AlertProps{
				Variant: ui.AlertError,
				Message: errorState.Get(),
			})
		}

		// Delete confirmation modal
		deleteModal := ui.Modal(ui.ModalProps{
			Open:    showDeleteModal.Get(),
			OnClose: func() { showDeleteModal.Set(false) },
			Title:   "Delete Client?",
			Size:    ui.ModalSM,
			Children: []core.Node{
				ui.ModalContent(ui.ModalContentProps{
					Children: []core.Node{
						core.P(core.Class("text-gray-600 dark:text-gray-300"),
							core.Text(fmt.Sprintf("Are you sure you want to delete %s? This action cannot be undone.", displayName)),
						),
					},
				}),
				ui.ModalFooter(ui.ModalFooterProps{
					Children: []core.Node{
						ui.Button(ui.ButtonProps{
							Variant:  ui.ButtonGhost,
							Children: []core.Node{core.Text("Cancel")},
							OnClick:  func() { showDeleteModal.Set(false) },
						}),
						ui.Button(ui.ButtonProps{
							Variant:  ui.ButtonDestructive,
							Children: []core.Node{core.Text("Delete")},
							OnClick:  confirmDelete,
						}),
					},
				}),
			},
		})

		return core.Frag(
			deleteModal,
			ui.PageHeader(ui.PageHeaderProps{
				Breadcrumbs: []ui.BreadcrumbItem{
					{Label: "Admin", Href: "/admin"},
					{Label: "Clients", Href: "/admin/clients"},
					{Label: displayName},
				},
				Title:   displayName,
				Actions: actions,
			}),
			errorNode,
			ui.Card(ui.CardProps{
				Children: []core.Node{
					ui.CardContent(ui.CardContentProps{
						Children: []core.Node{
							// Avatar and basic info header
							core.Div(core.Class("flex items-center gap-4 mb-6 pb-6 border-b border-gray-200 dark:border-gray-700"),
								// Avatar circle with initials
								core.Div(core.Class("w-16 h-16 rounded-full bg-blue-600 flex items-center justify-center text-white text-xl font-bold"),
									core.Text(initials),
								),
								core.Div(core.Attrs{},
									core.H2(core.Class("text-xl font-semibold text-gray-900 dark:text-white"),
										core.Text(displayName),
									),
									core.P(core.Class("text-gray-500 dark:text-gray-400"),
										core.Text(fmt.Sprintf("Client #%d", displayItem.ID)),
									),
								),
							),

							// Business
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Business"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						clientDetailRow("State", displayItem.State),
						clientDetailRow("Description", displayItem.Description),
								),
							),

							// Contact
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Contact"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						clientDetailRow("First Name", displayItem.FirstName),
						clientDetailRow("Last Name", displayItem.LastName),
						clientDetailRow("Email", displayItem.Email),
						clientDetailRow("Phone", displayItem.Phone),
								),
							),

							// Lead Info
							core.Div(core.Class("mb-6"),
								core.H3(core.Class("text-lg font-semibold text-gray-900 dark:text-white mb-4"),
									core.Text("Lead Info"),
								),
								core.Div(core.Class("grid grid-cols-1 md:grid-cols-2 gap-4"),
						clientDetailRow("Salesperson", func() string {
							if displayItem.Salesperson != nil {
								return displayItem.Salesperson.Name
							}
							return "-"
						}()),
						clientDetailRow("Closed Lead", func() string {
							if displayItem.ClosedLead {
								return "Yes"
							}
							return "No"
						}()),
								),
							),

							// Timestamps
							core.Div(core.Class("mt-6 pt-4 border-t border-gray-200 dark:border-gray-700"),
								clientDetailRow("Created", displayItem.CreatedAt.Format("Jan 2, 2006 3:04 PM")),
								clientDetailRow("Updated", displayItem.UpdatedAt.Format("Jan 2, 2006 3:04 PM")),
							),
						},
					}),
				},
			}),
		)
	}
}

func clientDetailRow(label, value string) core.Node {
	return core.Div(core.Class("py-2"),
		core.Div(core.Class("text-sm text-gray-500 dark:text-gray-400"),
			core.Text(label),
		),
		core.Div(core.Class("text-gray-900 dark:text-white font-medium"),
			core.Text(value),
		),
	)
}

// clientGetInitials extracts initials from a name for avatar display
func clientGetInitials(name string) string {
	if name == "" {
		return "?"
	}
	words := strings.Fields(name)
	if len(words) == 0 {
		runes := []rune(name)
		if len(runes) > 0 {
			return strings.ToUpper(string(runes[0]))
		}
		return "?"
	}
	if len(words) == 1 {
		runes := []rune(words[0])
		if len(runes) > 0 {
			return strings.ToUpper(string(runes[0]))
		}
		return "?"
	}
	first := []rune(words[0])
	last := []rune(words[len(words)-1])
	if len(first) > 0 && len(last) > 0 {
		return strings.ToUpper(string(first[0]) + string(last[0]))
	}
	return "?"
}
