// Code generated by gux model; DO NOT EDIT.
// This file contains shared helper functions for admin pages.
package admin

import (
	"strconv"
)

// parseUint converts a string to uint, returning 0 for empty strings
func parseUint(s string) uint {
	if s == "" {
		return 0
	}
	v, _ := strconv.ParseUint(s, 10, 64)
	return uint(v)
}

// parseUintPtr converts a string to *uint, returning nil for empty strings
func parseUintPtr(s string) *uint {
	if s == "" {
		return nil
	}
	v, _ := strconv.ParseUint(s, 10, 64)
	u := uint(v)
	return &u
}
