// Code generated by gux model; DO NOT EDIT.
// This file contains shared hook types for admin page customization.
// To add hooks, create a separate file (e.g., client_hooks.go) and set the hook variables in init().
package admin

import (
	"github.com/dougbarrett/gux/core"
)

// HookContext provides context to hook functions
type HookContext struct {
	Router *core.Router
}

// ListActionsHook adds buttons to the list page header (next to "Add X")
type ListActionsHook func(ctx HookContext) []core.Node

// ListRowActionsHook adds buttons per table row
// The generic parameter T is the DTO list type (e.g., dto.ClientList)
type ListRowActionsHook[T any] func(ctx HookContext, item T) []core.Node

// TableColumnDef defines a custom table column
type TableColumnDef struct {
	Header string
	Cell   func(item any) core.Node
}

// TableColumnsHook adds custom columns to the table
type TableColumnsHook func() []TableColumnDef

// DetailActionsHook adds buttons to the detail page (next to Edit/Delete)
// The generic parameter T is the DTO detail type (e.g., dto.ClientDetail)
type DetailActionsHook[T any] func(ctx HookContext, item T) []core.Node

// DetailSectionsHook adds sections to the detail page body
// The generic parameter T is the DTO detail type (e.g., dto.ClientDetail)
type DetailSectionsHook[T any] func(ctx HookContext, item T) []core.Node

// FormSectionsHook adds sections to create/edit forms
type FormSectionsHook func(ctx HookContext, isEdit bool) []core.Node

// BeforeSaveHook validates/transforms data before API call
// Return an error to cancel the save operation
type BeforeSaveHook func(ctx HookContext, data map[string]any, isEdit bool) error

// AfterSaveHook runs after a successful save operation
type AfterSaveHook func(ctx HookContext, id uint, isEdit bool)
