// Code generated by gux model; DO NOT EDIT.
// This file bridges admin hooks from the guxgen/admin package.
// Set hooks in a separate file (e.g., order_hooks.go) using the Set* functions.
package admin

import (
	gadmin "github.com/dougbarrett/gux/guxgen/admin"
	"github.com/dougbarrett/gux/guxgen/dto"
	"github.com/dougbarrett/gux/core"
)

// HookContext is re-exported from guxgen/admin for convenience
type HookContext = gadmin.HookContext

// Client hooks
// ----------------------------------------------------------------

// SetClientListActions sets the hook for adding buttons to the list page header
func SetClientListActions(fn func(HookContext) []core.Node) {
	gadmin.ClientListActions = fn
}

// SetClientListRowActions sets the hook for adding buttons per table row
func SetClientListRowActions(fn func(HookContext, dto.ClientList) []core.Node) {
	gadmin.ClientListRowActions = fn
}

// SetClientDetailActions sets the hook for adding buttons to the detail page
func SetClientDetailActions(fn func(HookContext, dto.ClientDetail) []core.Node) {
	gadmin.ClientDetailActions = fn
}

// SetClientDetailSections sets the hook for adding sections to the detail page
func SetClientDetailSections(fn func(HookContext, dto.ClientDetail) []core.Node) {
	gadmin.ClientDetailSections = fn
}

// SetClientFormSections sets the hook for adding sections to create/edit forms
func SetClientFormSections(fn func(HookContext, bool) []core.Node) {
	gadmin.ClientFormSections = fn
}

// SetClientBeforeSave sets the hook for validating/transforming data before save
func SetClientBeforeSave(fn func(HookContext, map[string]any, bool) error) {
	gadmin.ClientBeforeSave = fn
}

// SetClientAfterSave sets the hook for running logic after successful save
func SetClientAfterSave(fn func(HookContext, uint, bool)) {
	gadmin.ClientAfterSave = fn
}
