// Code generated by gux. DO NOT EDIT.
//go:build js && wasm

package api

import "fmt"


// PostsClient is a client for PostsAPI
type PostsClient struct {
	cfg *clientConfig
}

// NewPostsClient creates a new PostsClient
func NewPostsClient(opts ...ClientOption) *PostsClient {
	cfg := &clientConfig{
		baseURL:  "",
		basePath: "/api/posts",
	}
	for _, opt := range opts {
		opt(cfg)
	}
	return &PostsClient{cfg: cfg}
}


// GetAll fetches data via GET /api/posts/
func (c *PostsClient) GetAll() ([]Post, error) {
	return doRequest[[]Post](c.cfg, "GET", "/", nil)
}

// GetByID fetches data via GET /api/posts/{id}
func (c *PostsClient) GetByID(id int) (*Post, error) {
	result, err := doRequest[Post](c.cfg, "GET", fmt.Sprintf("/%d", id), nil)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create creates data via POST /api/posts/
func (c *PostsClient) Create(req CreatePostRequest) (*Post, error) {
	result, err := doRequest[Post](c.cfg, "POST", "/", req)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update updates data via PUT /api/posts/{id}
func (c *PostsClient) Update(id int, req CreatePostRequest) (*Post, error) {
	result, err := doRequest[Post](c.cfg, "PUT", fmt.Sprintf("/%d", id), req)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete deletes data via DELETE /api/posts/{id}
func (c *PostsClient) Delete(id int) error {
	return doRequestNoResponse(c.cfg, "DELETE", fmt.Sprintf("/%d", id))
}


