// Code generated by gux. DO NOT EDIT.

package api

import (
	"encoding/json"
	"net/http"
	"strconv"
	"strings"

	gqapi "github.com/dougbarrett/gux/api"
)


// PostsAPIHandler wraps a PostsAPI implementation with HTTP handlers
type PostsAPIHandler struct {
	service    PostsAPI
	middleware []func(http.Handler) http.Handler
}

// NewPostsAPIHandler creates a new HTTP handler for PostsAPI
func NewPostsAPIHandler(service PostsAPI) *PostsAPIHandler {
	return &PostsAPIHandler{service: service}
}

// Use adds middleware to the handler chain
func (h *PostsAPIHandler) Use(mw ...func(http.Handler) http.Handler) {
	h.middleware = append(h.middleware, mw...)
}

// wrap applies middleware chain to a handler
func (h *PostsAPIHandler) wrap(handler http.HandlerFunc) http.Handler {
	var result http.Handler = handler
	for i := len(h.middleware) - 1; i >= 0; i-- {
		result = h.middleware[i](result)
	}
	return result
}

// RegisterRoutes registers all routes for PostsAPI
func (h *PostsAPIHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.Handle("GET /api/posts/", h.wrap(h.handleGetAll))
	mux.Handle("GET /api/posts/{id}", h.wrap(h.handleGetByID))
	mux.Handle("POST /api/posts/", h.wrap(h.handleCreate))
	mux.Handle("PUT /api/posts/{id}", h.wrap(h.handleUpdate))
	mux.Handle("DELETE /api/posts/{id}", h.wrap(h.handleDelete))
}


func (h *PostsAPIHandler) handleGetAll(w http.ResponseWriter, r *http.Request) {

	result, err := h.service.GetAll(r.Context())
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleGetByID(w http.ResponseWriter, r *http.Request) {
	// Extract path parameters
	path := strings.TrimPrefix(r.URL.Path, "/api/posts")
	parts := strings.Split(strings.Trim(path, "/"), "/")
	_ = parts // avoid unused variable if no params extracted
	id, err := strconv.Atoi(parts[0])
	if err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid id: must be an integer"))
		return
	}

	result, err := h.service.GetByID(r.Context(), id)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleCreate(w http.ResponseWriter, r *http.Request) {
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid request body"))
		return
	}

	result, err := h.service.Create(r.Context(), req)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleUpdate(w http.ResponseWriter, r *http.Request) {
	// Extract path parameters
	path := strings.TrimPrefix(r.URL.Path, "/api/posts")
	parts := strings.Split(strings.Trim(path, "/"), "/")
	_ = parts // avoid unused variable if no params extracted
	id, err := strconv.Atoi(parts[0])
	if err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid id: must be an integer"))
		return
	}
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid request body"))
		return
	}

	result, err := h.service.Update(r.Context(), id, req)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleDelete(w http.ResponseWriter, r *http.Request) {
	// Extract path parameters
	path := strings.TrimPrefix(r.URL.Path, "/api/posts")
	parts := strings.Split(strings.Trim(path, "/"), "/")
	_ = parts // avoid unused variable if no params extracted
	id, err := strconv.Atoi(parts[0])
	if err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid id: must be an integer"))
		return
	}

	err = h.service.Delete(r.Context(), id)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}


