// Code generated by apigen. DO NOT EDIT.

package api

import (
	"encoding/json"
	"net/http"
	"strconv"
	"strings"
)


// PostsAPIHandler wraps a PostsAPI implementation with HTTP handlers
type PostsAPIHandler struct {
	service PostsAPI
}

// NewPostsAPIHandler creates a new HTTP handler for PostsAPI
func NewPostsAPIHandler(service PostsAPI) *PostsAPIHandler {
	return &PostsAPIHandler{service: service}
}

// RegisterRoutes registers all routes for PostsAPI
func (h *PostsAPIHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/api/posts", h.handleRoot)
	mux.HandleFunc("/api/posts/", h.handleWithID)
}

func (h *PostsAPIHandler) handleRoot(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		h.handleGetAll(w, r)
	case http.MethodPost:
		h.handleCreate(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (h *PostsAPIHandler) handleWithID(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/api/posts/")

	// Handle trailing slash - delegate to root handler
	if path == "" {
		h.handleRoot(w, r)
		return
	}

	id, err := strconv.Atoi(path)
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}

	switch r.Method {
	case http.MethodGet:
		h.handleGetByID(w, r, id)
	case http.MethodPut:
		h.handleUpdate(w, r, id)
	case http.MethodDelete:
		h.handleDelete(w, r, id)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}


func (h *PostsAPIHandler) handleGetAll(w http.ResponseWriter, r *http.Request) {

	result, err := h.service.GetAll(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleGetByID(w http.ResponseWriter, r *http.Request, id int) {

	result, err := h.service.GetByID(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleCreate(w http.ResponseWriter, r *http.Request) {
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	result, err := h.service.Create(r.Context(), req)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleUpdate(w http.ResponseWriter, r *http.Request, id int) {
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	result, err := h.service.Update(r.Context(), id, req)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleDelete(w http.ResponseWriter, r *http.Request, id int) {

	err := h.service.Delete(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}


