// Code generated by apigen. DO NOT EDIT.

package api

import (
	"encoding/json"
	"net/http"
	"strconv"
	"strings"

	gqapi "github.com/dougbarrett/gux/api"
)

// PostsAPIHandler wraps a PostsAPI implementation with HTTP handlers
type PostsAPIHandler struct {
	service    PostsAPI
	middleware []func(http.Handler) http.Handler
}

// NewPostsAPIHandler creates a new HTTP handler for PostsAPI
func NewPostsAPIHandler(service PostsAPI) *PostsAPIHandler {
	return &PostsAPIHandler{service: service}
}

// Use adds middleware to the handler chain
func (h *PostsAPIHandler) Use(mw ...func(http.Handler) http.Handler) {
	h.middleware = append(h.middleware, mw...)
}

// wrap applies middleware chain to a handler
func (h *PostsAPIHandler) wrap(handler http.HandlerFunc) http.Handler {
	var result http.Handler = handler
	for i := len(h.middleware) - 1; i >= 0; i-- {
		result = h.middleware[i](result)
	}
	return result
}

// RegisterRoutes registers all routes for PostsAPI
func (h *PostsAPIHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.Handle("/api/posts", h.wrap(h.handleRoot))
	mux.Handle("/api/posts/", h.wrap(h.handleWithID))
}

func (h *PostsAPIHandler) handleRoot(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		h.handleGetAll(w, r)
	case http.MethodPost:
		h.handleCreate(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (h *PostsAPIHandler) handleWithID(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/api/posts/")

	// Handle trailing slash - delegate to root handler
	if path == "" {
		h.handleRoot(w, r)
		return
	}

	id, err := strconv.Atoi(path)
	if err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid ID"))
		return
	}

	switch r.Method {
	case http.MethodGet:
		h.handleGetByID(w, r, id)
	case http.MethodPut:
		h.handleUpdate(w, r, id)
	case http.MethodDelete:
		h.handleDelete(w, r, id)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (h *PostsAPIHandler) handleGetAll(w http.ResponseWriter, r *http.Request) {

	result, err := h.service.GetAll(r.Context())
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleGetByID(w http.ResponseWriter, r *http.Request, id int) {

	result, err := h.service.GetByID(r.Context(), id)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleCreate(w http.ResponseWriter, r *http.Request) {
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid request body"))
		return
	}

	result, err := h.service.Create(r.Context(), req)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleUpdate(w http.ResponseWriter, r *http.Request, id int) {
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		gqapi.WriteError(w, gqapi.BadRequest("invalid request body"))
		return
	}

	result, err := h.service.Update(r.Context(), id, req)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *PostsAPIHandler) handleDelete(w http.ResponseWriter, r *http.Request, id int) {

	err := h.service.Delete(r.Context(), id)
	if err != nil {
		gqapi.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
